#!/usr/bin/env node
// mpd-ext — the developer CLI of the MPD extension interface (row `mpd-ext`).
//
// It shares ONE validator with the runtime: the descriptor is loaded with the
// plugin's own `buildExtension()` (packages/mpd-ext-plugin/src/registry.ts), the
// same function apply-time discovery calls. A manifest this CLI accepts is a
// manifest the loader accepts — there is deliberately no second rule set here,
// because "documented here, enforced differently there" is how a contract rots.
//
// Commands
//   validate <dir|mpd-ext.json>   exit 0 when the extension loads, exit 1 with one
//                                 line per item otherwise (CI-safe)
//   scaffold <name> [--dir <path>] [--with-mcp]
//                                 COPY templates/mpd-extension and rewrite its
//                                 placeholder names; --with-mcp keeps the stdio MCP
//                                 server (without it the copy drops that kind)
//   list                          what this host would discover, plane by plane
//   --self-test                   the CLI's own checks (temp dirs only)
//   --validator                   which validator this run actually loaded, and from where
//
// WHERE THE VALIDATOR COMES FROM (T-51): the CLI resolves its validator in two steps, and
// never re-implements a rule.
//   1. the TypeScript SOURCES (packages/mpd-ext-plugin/src/*.ts) — a checkout under bun, so
//      no build step can make the CLI validate a stale copy of the rules;
//   2. the COMPILED entry `packages/mpd-ext-plugin/dist/validator.js` — a packed artifact.
//      The packer copies `dist/` only (never `src/`), and the shipped bundle
//      (`dist/index.js`) exports just the plugin surface, so `scripts/pack-mpd.mjs` emits
//      this sidecar: the same compiled validator plus ONE `export { … }` line. Measured
//      before the fix: inside `dist/mpd-package/` every command died with `Cannot find
//      module '…/packages/mpd-ext-plugin/src/registry.ts'`.
// Step 2 is also what makes the packed CLI runnable under plain `node` (no TS loader).
//
// The `scaffold` template travels with the package too (`templates/mpd-extension`, T-35).
//
// Lives under scripts/ rather than skills/** on purpose: skills/** is
// VENDOR_LOCK-fingerprinted, and touching it would force a treeSha re-pin.
import { cpSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, extname, join, resolve, sep } from "node:path"
import { fileURLToPath } from "node:url"
import { spawnSync } from "node:child_process"

const scriptPath = fileURLToPath(import.meta.url)
const repoRoot = dirname(dirname(scriptPath))

// Step 1 targets: the live rules of a checkout. Kept as a table so the fatal diagnostic below
// can name every path it tried instead of one bare "Cannot find module".
const SOURCE_VALIDATOR = {
  registry: "../packages/mpd-ext-plugin/src/registry.ts",
  sdk: "../packages/mpd-ext-plugin/src/sdk.ts",
  manifest: "../packages/mpd-ext-plugin/src/manifest.ts",
  // The base-roster name table the runtime screens extension roles against: `registry.ts`
  // builds its private BASE_ROLE_NAME_KEYS from this same module, so the CLI screens with
  // the same table and the same `roleNameKey`, not with a re-implementation of either.
  rosterData: "../packages/mpd-roles-plugin/src/roles.data.ts",
}
// Step 2 target: the compiled entry a PACKED artifact carries, generated by
// `scripts/pack-mpd.mjs` (its VALIDATOR_SHIM_EXPORTS is the twin of this list, and
// `scripts/verify-pack-closure.mjs` fails when the two drift apart).
const COMPILED_VALIDATOR = "../packages/mpd-ext-plugin/dist/validator.js"
const REQUIRED_COMPILED_EXPORTS = [
  "ROLES",
  "MPD_EXT_CONTRACT",
  "buildExtension",
  "roleNameKey",
  "roleNameCollisionReason",
  "discoverPlane",
  "projectExtensionsDir",
  "userExtensionsDir",
  "bundleExtensionsDir",
]

function describeModuleError(error) {
  if (error === null || typeof error !== "object") return String(error)
  const tag = error.code ?? error.name
  return (tag === undefined ? "" : tag + ": ") + String(error.message ?? error)
}

/**
 * Load the ONE validator this CLI shares with the runtime, sources first, compiled entry
 * second. Never throws: a run with no validator prints every path it tried and exits 1 —
 * a validator-less CLI must never "validate" anything with a fallback rule set.
 */
async function loadSharedValidator() {
  const attempts = []
  const loaded = {}
  let complete = true
  for (const [key, rel] of Object.entries(SOURCE_VALIDATOR)) {
    try {
      loaded[key] = await import(new URL(rel, import.meta.url).href)
    } catch (error) {
      complete = false
      attempts.push({ target: rel, error: describeModuleError(error) })
    }
  }
  if (complete) {
    return { mode: "source", registry: loaded.registry, sdk: loaded.sdk, manifest: loaded.manifest, rosterData: loaded.rosterData, attempts }
  }
  try {
    const compiled = await import(new URL(COMPILED_VALIDATOR, import.meta.url).href)
    const missing = REQUIRED_COMPILED_EXPORTS.filter((name) => compiled[name] === undefined)
    if (missing.length === 0) {
      // In compiled mode all four namespaces ARE this one module: the bundle carries the
      // registry, the contract, the manifest helpers and the roster table.
      return { mode: "compiled", registry: compiled, sdk: compiled, manifest: compiled, rosterData: compiled, attempts, target: COMPILED_VALIDATOR }
    }
    attempts.push({ target: COMPILED_VALIDATOR, error: "loaded, but missing exports: " + missing.join(", ") })
  } catch (error) {
    attempts.push({ target: COMPILED_VALIDATOR, error: describeModuleError(error) })
  }
  process.stderr.write("mpd-ext: cannot load the shared validator — this CLI deliberately has no rule set of its own, so it refuses to run without one.\n")
  for (const attempt of attempts) process.stderr.write("  tried " + attempt.target + ": " + attempt.error + "\n")
  process.stderr.write("  from a checkout: run it under bun (`bun scripts/mpd-ext.mjs …`) so the TypeScript sources load\n")
  process.stderr.write("  from a packed artifact: re-run `npm run pack` — the packer emits packages/mpd-ext-plugin/dist/validator.js for exactly this case\n")
  process.exit(1)
}

const validator = await loadSharedValidator()
const registry = validator.registry
const sdk = validator.sdk
const manifest = validator.manifest
const rosterData = validator.rosterData
const BASE_ROLE_NAME_KEYS = new Set(rosterData.ROLES.map((role) => registry.roleNameKey(role.name)))

const MANIFEST_FILE = sdk.MPD_EXT_CONTRACT.manifestFile
const PLANES = ["project", "user", "bundle"]

function line(text) {
  process.stdout.write(text + "\n")
}

function fail(text) {
  process.stderr.write(text + "\n")
  process.exitCode = 1
}

/** A non-fatal problem: reported on stderr, and it never changes the exit code. */
function warn(text) {
  process.stderr.write(text + "\n")
}

/** Resolve `<dir>` (an extension directory) or a direct manifest path to {root, manifestPath}. */
function locateExtension(input) {
  const target = resolve(input ?? "")
  if (!existsSync(target)) return undefined
  if (statSync(target).isFile()) {
    if (target.endsWith(MANIFEST_FILE)) return { root: dirname(target), manifestPath: target }
    return undefined
  }
  const manifestPath = join(target, MANIFEST_FILE)
  if (!existsSync(manifestPath)) return undefined
  return { root: target, manifestPath }
}

/** Load one extension through the RUNTIME validator. Never throws. */
function loadExtension(input, plane = "user") {
  const located = locateExtension(input)
  if (located === undefined) {
    return { errors: [{ item: input ?? "", reason: `no ${MANIFEST_FILE} found at or under "${resolve(input ?? "")}"` }], entry: undefined, rejected: undefined }
  }
  let raw
  try {
    raw = readFileSync(located.manifestPath, "utf8")
  } catch (error) {
    return { errors: [{ item: located.manifestPath, reason: `cannot read: ${String(error)}` }], entry: undefined, rejected: undefined }
  }
  let parsed
  try {
    parsed = JSON.parse(raw)
  } catch (error) {
    return {
      errors: [{ item: located.manifestPath, reason: `invalid JSON: ${String(error)}` }],
      entry: undefined,
      rejected: { id: located.root, plane, origin: "directory", root: located.root, source: located.manifestPath, errors: [{ item: MANIFEST_FILE, reason: `invalid JSON: ${String(error)}` }] },
    }
  }
  const id = typeof parsed?.id === "string" && parsed.id.length > 0 ? parsed.id : "unnamed"
  try {
    const built = registry.buildExtension({
      input: parsed,
      plane,
      origin: "directory",
      root: located.root,
      source: located.manifestPath,
      fallbackId: id,
      providerName: `mpd-ext:${id}`,
    })
    if (built.rejected !== undefined) return { errors: built.rejected.errors, entry: undefined, rejected: built.rejected }
    return { errors: built.entry.errors, entry: built.entry, rejected: undefined }
  } catch (error) {
    return { errors: [{ item: MANIFEST_FILE, reason: `validation crashed: ${String(error)}` }], entry: undefined, rejected: undefined }
  }
}

function describeEntry(entry) {
  const counts = entry.contributions
  return `${counts.skills} skill(s), ${counts.flows} flow(s), ${counts.roles} role(s), ${counts.mcp} mcp server(s)`
}

/** `validate <dir>` — the CI gate. */
function runValidate(input, plane) {
  if (input === undefined) {
    fail("mpd-ext validate: an extension directory is required")
    return
  }
  const result = loadExtension(input, plane)
  const id = result.entry?.id ?? result.rejected?.id ?? resolve(input)
  line(`[mpd-ext] validate ${resolve(input)} (plane=${plane})`)
  line(`  extension "${id}": ${result.entry === undefined ? "REJECTED" : "loadable"}`)
  if (result.entry !== undefined) line(`  contributes: ${describeEntry(result.entry)}`)
  for (const error of result.errors) line(`  error ${error.item}: ${error.reason}`)
  for (const pending of result.entry?.pending ?? []) line(`  pending ${pending.item}: ${pending.reason}`)
  if (result.errors.length > 0) {
    fail(`[mpd-ext] ${result.errors.length} problem(s) — this extension would not load`)
    return
  }
  line("[mpd-ext] ok")
}

/** `list` — what this host would discover. */
function runList() {
  const roots = [
    ["project", manifest.projectExtensionsDir(process.cwd())],
    ["user", manifest.userExtensionsDir()],
    ["bundle", manifest.bundleExtensionsDir()],
  ]
  const seen = new Map()
  let problems = 0
  for (const [plane, dir] of roots) {
    line(`[mpd-ext] ${plane} plane: ${dir}`)
    const discovered = manifest.discoverPlane({ plane, dir, providerNameFor: (id) => `mpd-ext:${id}`, warn: (text) => { problems += 1; line(`  warn: ${text}`) } })
    for (const entry of discovered.entries) {
      if (seen.has(entry.id)) {
        line(`  ${entry.id}: shadowed by the ${seen.get(entry.id)} plane (first wins)`)
        continue
      }
      seen.set(entry.id, plane)
      line(`  ${entry.id}: ${entry.enabled ? "enabled" : "disabled"} — ${describeEntry(entry)}${entry.errors.length > 0 ? ` — ${entry.errors.length} error(s)` : ""}`)
      for (const error of entry.errors) line(`    error ${error.item}: ${error.reason}`)
    }
    for (const rejected of discovered.rejected) {
      problems += 1
      line(`  ${rejected.id}: REJECTED — ${rejected.errors.map((error) => `${error.item}: ${error.reason}`).join("; ")}`)
    }
    if (discovered.entries.length === 0 && discovered.rejected.length === 0) line("  (none)")
  }
  if (problems > 0) {
    line(`[mpd-ext] ${problems} problem(s) recorded (the loader still boots: every failure is contained per item)`)
  }
}

/**
 * The generic template — the ONLY source of truth for what `scaffold` emits.
 *
 * The placeholder to rewrite is the template manifest's OWN `id`, so this CLI
 * knows no derived-name pattern at all: it renames paths and rewrites text.
 */
const TEMPLATE_DIR = join(repoRoot, "templates", "mpd-extension")
const TEXT_EXTENSIONS = [".json", ".md", ".mjs"]

/**
 * The contract's own `serverName` bound, parsed OUT of the contract pattern — never the
 * literal 32 — so widening the contract widens this CLI with it.
 */
function serverNameMaxLength() {
  const match = /\{1,(\d+)\}/.exec(sdk.MPD_EXT_CONTRACT.serverNamePattern)
  if (match === null) {
    fail(`mpd-ext: cannot read a maximum length out of the contract's serverName pattern ${sdk.MPD_EXT_CONTRACT.serverNamePattern}`)
    return undefined
  }
  return Number(match[1])
}

/** The derived `serverName`: the extension name, capped by the contract's own bound. */
function serverNameFor(name) {
  return name.slice(0, serverNameMaxLength() ?? name.length)
}

/** The placeholder token, read FROM the template (never hard-coded here). */
function templateToken() {
  return JSON.parse(readFileSync(join(TEMPLATE_DIR, MANIFEST_FILE), "utf8")).id
}

/** The derived names the copy will carry, read from the template's OWN paths and manifest. */
function templateDerivedNames(token, name) {
  const rename = (value) => value.split(token).join(name)
  const skillsRoot = join(TEMPLATE_DIR, "skills")
  const flowsRoot = join(TEMPLATE_DIR, "flows")
  const skillDirs = existsSync(skillsRoot)
    ? readdirSync(skillsRoot, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => rename(entry.name))
    : []
  const flowIds = existsSync(flowsRoot)
    ? readdirSync(flowsRoot)
        .filter((entry) => entry.endsWith(".json"))
        .map((entry) => rename(entry.slice(0, -".json".length)))
    : []
  const templateManifest = JSON.parse(readFileSync(join(TEMPLATE_DIR, MANIFEST_FILE), "utf8"))
  const roleNames = (templateManifest.contributes?.roles ?? []).map((item) => rename(String(item.name)))
  return { skillDirs, flowIds, roleNames }
}

/**
 * The base roster screens an extension role by its collapsed name key and always wins
 * (`packages/mpd-ext-plugin/src/registry.ts:746-748`). Screen it HERE, before a single
 * byte is written, and report it with the roster's own sentence
 * (`roleNameCollisionReason`, `registry.ts:236-238`) instead of as a CLI defect.
 */
function baseRosterRoleConflicts(name, roleNames) {
  const conflicts = []
  roleNames.forEach((roleName, index) => {
    if (BASE_ROLE_NAME_KEYS.has(registry.roleNameKey(roleName))) {
      conflicts.push(registry.roleNameCollisionReason(name, roleName, `contributes.roles[${index}]`, "the base roster"))
    }
  })
  return conflicts
}

/** Copy the template tree, renaming every path segment and rewriting every text body. */
function copyTemplateTree(sourceRoot, targetRoot, token, name) {
  const copied = []
  const walk = (relative) => {
    const sourceDir = relative === "" ? sourceRoot : join(sourceRoot, relative)
    for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
      const child = relative === "" ? entry.name : join(relative, entry.name)
      const renamed = child
        .split(sep)
        .map((segment) => segment.split(token).join(name))
        .join(sep)
      const destination = join(targetRoot, renamed)
      if (entry.isDirectory()) {
        mkdirSync(destination, { recursive: true })
        walk(child)
        continue
      }
      const body = readFileSync(join(sourceRoot, child), "utf8")
      writeFileSync(destination, TEXT_EXTENSIONS.includes(extname(entry.name)) ? body.split(token).join(name) : body)
      copied.push(renamed)
    }
  }
  walk("")
  return copied
}

/**
 * The two documented manifest edits on top of the copy: the contract caps
 * `serverName` at 32 characters, and WITHOUT `--with-mcp` the `mcp` contribution
 * (and its server file) is dropped, so the default copy contributes three kinds.
 */
function finishManifest(target, name, withMcp) {
  const manifestPath = join(target, MANIFEST_FILE)
  const parsed = JSON.parse(readFileSync(manifestPath, "utf8"))
  const contributes = parsed.contributes ?? {}
  if (!withMcp) delete contributes.mcp
  if (Array.isArray(contributes.mcp)) {
    contributes.mcp = contributes.mcp.map((item) => ({ ...item, serverName: serverNameFor(name) }))
  }
  parsed.contributes = contributes
  writeFileSync(manifestPath, JSON.stringify(parsed, null, 2) + "\n")
  if (!withMcp) rmSync(join(target, "server.mjs"), { force: true })
}

/**
 * The per-file comparison A3 requires: a copy is the template modulo the token
 * rewrite and the documented `--with-mcp` drop — proven file by file, never
 * asserted in prose. Returns one line per difference (empty means equivalent).
 */
function compareCopyToTemplate(templateRoot, copyRoot, token, name, withMcp) {
  const problems = []
  const rename = (value) => value.split(token).join(name)
  const expected = new Set()
  const walk = (relative) => {
    const sourceDir = relative === "" ? templateRoot : join(templateRoot, relative)
    for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
      const child = relative === "" ? entry.name : join(relative, entry.name)
      if (entry.isDirectory()) {
        walk(child)
        continue
      }
      const target = child.split(sep).map(rename).join(sep)
      expected.add(target)
      const source = readFileSync(join(templateRoot, child), "utf8")
      if (!withMcp && child === "server.mjs") {
        if (existsSync(join(copyRoot, target))) problems.push(`${target}: the default copy must drop the mcp server`)
        continue
      }
      if (!existsSync(join(copyRoot, target))) {
        problems.push(`${target}: missing from the copy`)
        continue
      }
      const wantText = TEXT_EXTENSIONS.includes(extname(child)) ? source.split(token).join(name) : source
      const gotText = readFileSync(join(copyRoot, target), "utf8")
      if (child === MANIFEST_FILE) {
        const wantObject = JSON.parse(wantText)
        const wantContributes = wantObject.contributes ?? {}
        if (!withMcp) delete wantContributes.mcp
        if (Array.isArray(wantContributes.mcp)) {
          wantContributes.mcp = wantContributes.mcp.map((item) => ({ ...item, serverName: serverNameFor(name) }))
        }
        wantObject.contributes = wantContributes
        if (gotText !== JSON.stringify(wantObject, null, 2) + "\n") {
          problems.push(`${target}: manifest bytes differ from the canonical token-rewritten template (mcp ${withMcp ? "kept" : "dropped"})`)
        }
        continue
      }
      if (gotText !== wantText) problems.push(`${target}: bytes differ from the template modulo the token rewrite`)
    }
  }
  walk("")
  const extra = []
  const walkCopy = (relative) => {
    const dir = relative === "" ? copyRoot : join(copyRoot, relative)
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const child = relative === "" ? entry.name : join(relative, entry.name)
      if (entry.isDirectory()) walkCopy(child)
      else if (!expected.has(child)) extra.push(child)
    }
  }
  walkCopy("")
  for (const path of extra) problems.push(`${path}: not part of the template`)
  return problems
}

/**
 * `scaffold <name> --dir <path> [--with-mcp]` — COPY `templates/mpd-extension/`
 * and rewrite its placeholder (the template manifest's own id). The template is
 * the single source of truth: this CLI emits no code of its own.
 */
function runScaffold(name, options) {
  if (typeof name !== "string" || name.length === 0) {
    fail("mpd-ext scaffold: an extension name is required")
    return
  }
  if (!new RegExp(sdk.MPD_EXT_CONTRACT.idPattern).test(name)) {
    fail(`mpd-ext scaffold: "${name}" must match ${sdk.MPD_EXT_CONTRACT.idPattern}`)
    return
  }
  if (!existsSync(join(TEMPLATE_DIR, MANIFEST_FILE))) {
    fail(`mpd-ext scaffold: the template "${TEMPLATE_DIR}" is missing — it is the only source of this command's output`)
    return
  }
  const token = templateToken()
  if (typeof token !== "string" || token.length === 0) {
    fail("mpd-ext scaffold: the template manifest carries no placeholder id, so a copy cannot be named")
    return
  }
  const derived = templateDerivedNames(token, name)
  for (const [label, values] of [["skill name", derived.skillDirs], ["flow id", derived.flowIds]]) {
    for (const value of values) {
      if (!new RegExp(sdk.MPD_EXT_CONTRACT.skillNamePattern).test(value)) {
        fail(`mpd-ext scaffold: the derived ${label} "${value}" violates the skill-name grammar ${sdk.MPD_EXT_CONTRACT.skillNamePattern} — pick a name without a trailing dash`)
        return
      }
    }
  }
  const parent = resolve(options.dir ?? ".")
  const target = join(parent, name)
  if (existsSync(target)) {
    fail(`mpd-ext scaffold: "${target}" already exists — scaffolding never overwrites`)
    return
  }
  const roleConflicts = baseRosterRoleConflicts(name, derived.roleNames)
  if (roleConflicts.length > 0) {
    fail(`mpd-ext scaffold: refused — "${name}" would declare a role name the base roster already owns`)
    warn(`  nothing was written to ${target}`)
    for (const reason of roleConflicts) line(`  refused: ${reason}`)
    return
  }
  const withMcp = options.withMcp === true
  const maxServerName = serverNameMaxLength() ?? name.length
  if (name.length > maxServerName) {
    warn(`mpd-ext scaffold: warning: ${sdk.MPD_EXT_CONTRACT.serverNamePattern} caps serverName at ${maxServerName} characters, so the copy declares "${serverNameFor(name)}" instead of "${name}"`)
  }

  // Build in a STAGING container beside the target and move it into place only after the
  // runtime validator accepts it: a refusal (a CONTRACT refusal, never a CLI defect) can
  // then never leave a half-written, unloadable extension behind. The container level is
  // deliberate — discovery inspects only a root's IMMEDIATE children for `mpd-ext.json`,
  // so an extension staged one level down is never discoverable while it is being built.
  const stagingContainer = join(parent, `.mpd-ext-scaffold-${process.pid}-${Date.now()}`)
  const stagingTarget = join(stagingContainer, name)
  try {
    mkdirSync(stagingTarget, { recursive: true })
    const copied = copyTemplateTree(TEMPLATE_DIR, stagingTarget, token, name)
    finishManifest(stagingTarget, name, withMcp)

    const result = loadExtension(stagingTarget, "user")
    if (result.errors.length > 0 || result.entry === undefined) {
      fail(`mpd-ext scaffold: refused — the copy would not load as "${name}"; nothing was written to ${target}`)
      for (const error of result.errors) line(`  error ${error.item}: ${error.reason}`)
      return
    }
    renameSync(stagingTarget, target)
    line(`[mpd-ext] scaffolded "${name}" at ${target}`)
    line(`  copied ${copied.length} file(s) from templates/mpd-extension${withMcp ? "" : " (the mcp contribution and server.mjs were dropped)"}`)
    line(`  contributes: ${describeEntry(result.entry)}`)
    line(`  next: bun scripts/mpd-ext.mjs validate ${target}`)
  } finally {
    // a no-op after a successful rename; the only tree it removes is a refused staging one
    rmSync(stagingContainer, { recursive: true, force: true })
  }
}

// ── self-test ───────────────────────────────────────────────────────────────

function runChild(args) {
  const result = spawnSync(process.execPath, [scriptPath, ...args], { encoding: "utf8" })
  return { status: result.status, stdout: result.stdout ?? "", stderr: result.stderr ?? "" }
}

function selfTest() {
  const sandbox = mkdtempSync(join(tmpdir(), "mpd-ext-cli-selftest-"))
  let checks = 0
  const expect = (condition, label) => {
    checks += 1
    if (condition) line(`  ok ${label}`)
    else fail(`  FAIL ${label}`)
  }
  try {
    // 0. the shared validator surface. Both modes must expose the same four namespaces: in a
    //    checkout they are the sources, in a packed artifact they are the packer-generated
    //    compiled entry. A partially-populated shim passes an import and still breaks the
    //    commands, so assert the surfaces the CLI actually calls.
    expect(
      typeof registry.buildExtension === "function" &&
        typeof registry.roleNameKey === "function" &&
        typeof registry.roleNameCollisionReason === "function" &&
        typeof sdk.MPD_EXT_CONTRACT?.manifestFile === "string" &&
        typeof manifest.discoverPlane === "function" &&
        typeof manifest.projectExtensionsDir === "function" &&
        typeof manifest.userExtensionsDir === "function" &&
        typeof manifest.bundleExtensionsDir === "function" &&
        Array.isArray(rosterData.ROLES),
      `the shared validator exposes the four surfaces the CLI uses (${validator.mode} mode)`,
    )

    // 1. the template is the source of truth, so it must load with all four kinds.
    const template = runChild(["validate", TEMPLATE_DIR])
    expect(template.status === 0, `validate accepts templates/mpd-extension (got ${template.status}): ${template.stderr.trim()}`)
    expect(template.stdout.includes("1 skill(s), 1 flow(s), 1 role(s), 1 mcp server(s)"), "the template declares all four contribution kinds")

    // 2. --with-mcp: the copy keeps all four kinds and IS the template, file by file.
    const scaffold = runChild(["scaffold", "demo-ext", "--dir", sandbox, "--with-mcp"])
    expect(scaffold.status === 0, `scaffold --with-mcp exits 0 (got ${scaffold.status}): ${scaffold.stderr.trim()}`)
    const scaffolded = join(sandbox, "demo-ext")
    expect(existsSync(join(scaffolded, MANIFEST_FILE)), "scaffold wrote mpd-ext.json")
    for (const asset of ["skills/demo-ext-skill/SKILL.md", "flows/demo-ext-flow.json", "personas/demo-ext-reviewer.md", "server.mjs"]) {
      expect(existsSync(join(scaffolded, asset)), `scaffold wrote ${asset}`)
    }
    const validated = runChild(["validate", scaffolded])
    expect(validated.status === 0, `validate accepts the scaffold (got ${validated.status}): ${validated.stderr.trim()}`)
    const withMcpProblems = compareCopyToTemplate(TEMPLATE_DIR, scaffolded, templateToken(), "demo-ext", true)
    expect(withMcpProblems.length === 0, `the --with-mcp copy is the template modulo the token rewrite, file by file${withMcpProblems.length > 0 ? `: ${withMcpProblems.join("; ")}` : ""}`)

    // 3. the default arm: the copy DROPS the mcp contribution and its server file, and still loads.
    const plain = runChild(["scaffold", "demo-ext-plain", "--dir", sandbox])
    expect(plain.status === 0, `scaffold (no flag) exits 0 (got ${plain.status}): ${plain.stderr.trim()}`)
    const plainRoot = join(sandbox, "demo-ext-plain")
    expect(!existsSync(join(plainRoot, "server.mjs")), "the default copy drops server.mjs")
    expect(JSON.parse(readFileSync(join(plainRoot, MANIFEST_FILE), "utf8")).contributes.mcp === undefined, "the default copy drops the manifest mcp entry")
    for (const asset of ["skills/demo-ext-plain-skill/SKILL.md", "flows/demo-ext-plain-flow.json", "personas/demo-ext-plain-reviewer.md"]) {
      expect(existsSync(join(plainRoot, asset)), `the default copy wrote ${asset}`)
    }
    const plainValidated = runChild(["validate", plainRoot])
    expect(plainValidated.status === 0, `validate accepts the default copy (got ${plainValidated.status}): ${plainValidated.stderr.trim()}`)
    expect(plainValidated.stdout.includes("1 skill(s), 1 flow(s), 1 role(s), 0 mcp server(s)"), "the default copy contributes three kinds")
    const plainProblems = compareCopyToTemplate(TEMPLATE_DIR, plainRoot, templateToken(), "demo-ext-plain", false)
    expect(plainProblems.length === 0, `the default copy is the template modulo the token rewrite and the mcp drop, file by file${plainProblems.length > 0 ? `: ${plainProblems.join("; ")}` : ""}`)

    // 3b. an id longer than the contract's serverName bound: the cap comes from the contract
    //     pattern, it is WARNED rather than silent, and the copy still validates.
    const longId = "demo-ext-with-a-very-long-identifier-1234"
    const bound = serverNameMaxLength()
    const longRun = runChild(["scaffold", longId, "--dir", sandbox, "--with-mcp"])
    expect(longRun.status === 0, `scaffold accepts an id longer than the serverName bound (got ${longRun.status}): ${longRun.stderr.trim()}`)
    const longManifest = JSON.parse(readFileSync(join(sandbox, longId, MANIFEST_FILE), "utf8"))
    expect(longId.length > bound, `the long-id fixture (${longId.length} chars) really is longer than the contract bound (${bound})`)
    expect(longManifest.contributes.mcp[0].serverName === longId.slice(0, bound), `the copied serverName is capped at the contract bound (${bound}), not at a literal`)
    expect(longRun.stderr.includes("caps serverName at"), "the cap is WARNED on stderr, never silent")
    expect(runChild(["validate", join(sandbox, longId)]).status === 0, "the long-id copy still validates")

    // 4. the refusals: a bad id, an existing target, and a DERIVED ROLE NAME the base roster owns.
    const badName = runChild(["scaffold", "Bad Name", "--dir", sandbox])
    expect(badName.status === 1, "scaffold refuses an id that violates the id grammar")
    expect(badName.stderr.includes("must match"), "the refusal names the id grammar")
    const existing = runChild(["scaffold", "demo-ext", "--dir", sandbox])
    expect(existing.status === 1, "scaffold refuses an existing target")
    expect(existing.stderr.includes("already exists"), "the refusal says the target exists")

    // "plan" is the one reachable id whose derived role name ("plan reviewer") collapses onto a
    // base-roster name key (roleNameKey("Plan Reviewer")); it is refused BEFORE anything is written,
    // with the roster's own sentence, and it leaves nothing behind at the target.
    const collidingId = "plan"
    const collision = runChild(["scaffold", collidingId, "--dir", sandbox])
    expect(collision.status === 1, `scaffold refuses the base-roster role collision for id "plan" (got ${collision.status})`)
    expect(collision.stderr.includes("would declare a role name the base roster already owns"), "the refusal is a CONTRACT refusal, not a CLI-defect message")
    expect(collision.stdout.includes("is already taken by the base roster"), "the refusal quotes the roster's own collision sentence")
    expect(collision.stderr.includes("nothing was written"), "the refusal states that nothing was written")
    expect(!existsSync(join(sandbox, collidingId)), "a refused scaffold leaves nothing at the target")
    expect(!readdirSync(sandbox).some((entry) => entry.startsWith(".mpd-ext-scaffold")), "a refused scaffold leaves no staging container behind")

    // 5. a deliberately broken extension: every defect is reported, exit is 1.
    const broken = join(sandbox, "broken-ext")
    mkdirSync(broken, { recursive: true })
    writeFileSync(
      join(broken, MANIFEST_FILE),
      JSON.stringify({
        apiVersion: 1,
        id: "broken-ext",
        typoKey: true,
        contributes: {
          skills: [{ root: "../outside" }],
          mcp: [{ serverName: "not a name!", transport: "stdio", command: "node", surprise: 1 }],
          roles: [{ name: "Missing persona", persona: "personas/absent.md" }],
        },
      }),
    )
    const brokenRun = runChild(["validate", broken])
    expect(brokenRun.status === 1, `validate exits 1 on a broken extension (got ${brokenRun.status})`)
    for (const needle of ["typoKey", "serverName", "contributes.skills[0].root", "escapes are rejected", "surprise", "persona file does not exist"]) {
      expect(brokenRun.stdout.includes(needle), `the broken run reports "${needle}"`)
    }

    // 6. the negative control on a COPY of the template: per-item errors, exit 1.
    const brokenCopy = join(sandbox, "broken-copy")
    cpSync(scaffolded, brokenCopy, { recursive: true })
    writeFileSync(
      join(brokenCopy, MANIFEST_FILE),
      JSON.stringify({
        apiVersion: 1,
        id: "broken-copy",
        typoKey: true,
        contributes: {
          skills: [{ root: "skills" }],
          mcp: [{ serverName: "not a name!", transport: "stdio", command: "node", surprise: 1 }],
          roles: [{ name: "Missing persona", persona: "personas/absent.md" }],
        },
      }),
    )
    writeFileSync(join(brokenCopy, "skills", "demo-ext-skill", "SKILL.md"), "this file lost its YAML frontmatter\n")
    const brokenCopyRun = runChild(["validate", brokenCopy])
    expect(brokenCopyRun.status === 1, `validate exits 1 on a deliberately broken copy of the template (got ${brokenCopyRun.status})`)
    for (const needle of ["typoKey", "surprise", "serverName", "persona file does not exist", "frontmatter"]) {
      expect(brokenCopyRun.stdout.includes(needle), `the broken copy reports "${needle}"`)
    }

    // 7. the shipped example validates.
    const example = runChild(["validate", join(repoRoot, "extensions", "mpd-ext-example")])
    expect(example.status === 0, `validate accepts extensions/mpd-ext-example (got ${example.status}): ${example.stderr.trim()}`)

    // 8. list never throws and sees the bundle plane.
    const listed = runChild(["list"])
    expect(listed.status === 0, `list exits 0 (got ${listed.status})`)
    expect(listed.stdout.includes("bundle plane"), "list names the bundle plane")
    expect(listed.stdout.includes("mpd-ext-example"), "list sees the shipped example")

    // 9. usage guard.
    const usage = runChild([])
    expect(usage.stdout.includes("usage") || usage.status !== 0, "no command prints usage or fails")

    if (process.exitCode !== 1) line(`[mpd-ext] --self-test passed (${checks} checks) [validator: ${validator.mode}]`)
  } finally {
    rmSync(sandbox, { recursive: true, force: true })
  }
}

const USAGE = `usage: bun scripts/mpd-ext.mjs <command>

  validate <dir|mpd-ext.json> [--plane project|user|bundle]
  scaffold <name> [--dir <path>] [--with-mcp]
  list
  --self-test
  --validator

Runs from a checkout (bun: the TypeScript validator sources) and from a packed
artifact (the packer-generated packages/mpd-ext-plugin/dist/validator.js, which
also works under plain node). --validator prints which one this run loaded.`

async function main() {
  const argv = process.argv.slice(2)
  const command = argv[0]
  const flag = (name) => {
    const index = argv.indexOf(name)
    return index === -1 ? undefined : argv[index + 1]
  }
  if (command === "--self-test") return selfTest()
  if (command === "--validator") {
    line(`[mpd-ext] validator: ${validator.mode}`)
    const target = validator.mode === "compiled" ? [COMPILED_VALIDATOR] : Object.values(SOURCE_VALIDATOR)
    for (const rel of target) line(`  ${resolve(repoRoot, rel.replace(/^\.\.\//, ""))}`)
    if (validator.mode === "compiled") for (const attempt of validator.attempts) line(`  (source path unavailable: ${attempt.target}: ${attempt.error})`)
    return
  }
  if (command === "validate") {
    const plane = flag("--plane")
    return runValidate(argv[1], PLANES.includes(plane) ? plane : "user")
  }
  if (command === "scaffold") {
    return runScaffold(argv[1], { dir: flag("--dir"), withMcp: argv.includes("--with-mcp") })
  }
  if (command === "list") return runList()
  line(USAGE)
  if (command !== undefined && command !== "help" && command !== "--help") process.exitCode = 2
}

await main()
