// GENERATED by scripts/gen-roles.mjs — the OMO-origin agent roster (subagent definitions).
// Do not edit by hand: regenerate with `node scripts/gen-roles.mjs` after a persona/
// chain change. Main consumer surfaces: mpd_roles_list / mpd_role_spawn /
// mpd_team_spawn (role lookup) and mpd_modelchain_resolve (chain lookup).
export interface MpdRoleSpec {
  id: string
  name: string
  description: string
  /** Read-only roles spawn with a write-tool deny filter; workers spawn unrestricted. */
  readonly: boolean
  chain: Array<{ provider: string; model: string }>
  personaFile: string
}

export const ROLES: MpdRoleSpec[] = [
  {
    "id": "oracle",
    "name": "Oracle (Review/Architecture Advisor)",
    "description": "DeepSeek-adapted Oracle strategic technical advisor preset: architecture review, deep debugging, self-review.",
    "readonly": true,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-pro"
      },
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/oracle.md"
  },
  {
    "id": "librarian",
    "name": "Librarian (Open-Source Search)",
    "description": "DeepSeek-adapted Librarian evidence-based open-source code search preset (AST/LSP/web evidence collection).",
    "readonly": true,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      },
      {
        "provider": "deepseek",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/librarian.md"
  },
  {
    "id": "prometheus",
    "name": "Prometheus (Planning)",
    "description": "DeepSeek-adapted Prometheus planning advisor preset: produce only .mpd/plans plans, never implement.",
    "readonly": true,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-pro"
      },
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/prometheus.md"
  },
  {
    "id": "hephaestus",
    "name": "Hephaestus (Configuration Management)",
    "description": "mpd-dsh configuration management preset: explain profile/bundle/preset configuration, and produce diffs read-only.",
    "readonly": false,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      },
      {
        "provider": "deepseek",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/hephaestus.md"
  },
  {
    "id": "sisyphus",
    "name": "Sisyphus (primary coder)",
    "description": "Primary engineering agent: plan small, execute with tools, verify, report honestly.",
    "readonly": false,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-pro"
      },
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      },
      {
        "provider": "deepseek",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/sisyphus.md"
  },
  {
    "id": "atlas",
    "name": "Atlas (orchestrator)",
    "description": "Orchestrator: plan macro, delegate roles to subagents/teams, integrate results.",
    "readonly": false,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-pro"
      },
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/atlas.md"
  },
  {
    "id": "explore",
    "name": "Explore (read-only explorer)",
    "description": "Read-only codebase explorer: evidence-based answers, never edits.",
    "readonly": true,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      },
      {
        "provider": "deepseek",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/explore.md"
  },
  {
    "id": "metis",
    "name": "Metis (deep reviewer)",
    "description": "Deep reviewer: correctness/risk findings with evidence, no fixes.",
    "readonly": false,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-pro"
      },
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/metis.md"
  },
  {
    "id": "momus",
    "name": "Momus (UI/UX critic)",
    "description": "UI/UX and interaction critic: concrete, testable critiques.",
    "readonly": true,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      },
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-pro"
      }
    ],
    "personaFile": "personas/momus.md"
  },
  {
    "id": "multimodal-looker",
    "name": "Multimodal Looker (visual analyst)",
    "description": "Image/diagram analyst: read screenshots/diagrams and describe precisely.",
    "readonly": true,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash-vision-exp"
      },
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/multimodal-looker.md"
  },
  {
    "id": "sisyphus-junior",
    "name": "Sisyphus Junior (fast executor)",
    "description": "Fast executor: small, well-scoped mechanical changes with quick verification.",
    "readonly": false,
    "chain": [
      {
        "provider": "deepseek-official",
        "model": "deepseek-v4-flash"
      },
      {
        "provider": "deepseek",
        "model": "deepseek-v4-flash"
      }
    ],
    "personaFile": "personas/sisyphus-junior.md"
  }
]

export const ROLE_BY_ID: Record<string, MpdRoleSpec> = Object.fromEntries(ROLES.map((r) => [r.id, r]))
