// Generated by mount-lazy-live.mjs: a provider row that provides `mpdDsh` and then keeps its
// own fiber non-ACTIVE for SLOW_MS, so a SIBLING consumer row's first use lands inside the
// transient window (registered-but-not-ACTIVE) that T-50 is about.
import { createDshAdapter, SERVICE_NAME } from "/root/dshProj/my-power-dsh/packages/mpd-dsh-adapter-plugin/dist/index.js"
export const name = 't40-slow-adapter-probe'
export async function apply(ctx) {
  const adapter = createDshAdapter(ctx)
  ctx.provide(SERVICE_NAME, adapter)
  console.log('[t40-slow-adapter] mpdDsh provided; fiber stays non-ACTIVE for 6000 ms')
  await new Promise((resolve) => setTimeout(resolve, 6000))
  console.log('[t40-slow-adapter] apply returning — provider fiber becomes ACTIVE')
}
