// "No other line changes" proof for the bridge lane (t5, AC7): strip every `//#region mpd-delta …`
// span (markers AND body) from BOTH the committed revision and the working tree, write both
// projections to disk, and diff them with a REAL line diff (`git diff --no-index -U0`).
//
// What the output means:
//   - a `-` line in a bridged file  = adopted code whose replacement now lives inside a region. Fine.
//   - a `+` line in a bridged file  = a line ADDED OUTSIDE every region. That is the violation AC7
//     forbids, and this script exits 1 on it.
//   - any diff line in an EDIT-FREE adopted file = also a violation.
//
// Run: node evidence/agent-teams/adapter-wiring/bridge/region-diff-proof.mjs
import { execFileSync } from "node:child_process"
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..", "..", "..")
const libDir = join(repoRoot, "packages/mpd-agent-teams-plugin/lib")
const outDir = join(here, "projections")
mkdirSync(outDir, { recursive: true })

/** Remove every region (markers + body) from one source text. */
function stripRegions(source) {
    const lines = source.split("\n")
    const kept = []
    for (let index = 0; index < lines.length; index += 1) {
        const id = /^\s*\/\/#region (mpd-delta [A-Za-z0-9-]+) \(/.exec(lines[index])?.[1]
        if (id === undefined) {
            kept.push(lines[index])
            continue
        }
        const end = lines.findIndex((line, at) => at > index && line.trim() === `//#endregion ${id}`)
        if (end === -1) throw new Error(`unterminated region ${id} at line ${index + 1}`)
        index = end
    }
    return kept.join("\n")
}

const BRIDGED = ["index.js", "capabilities.js", "harness-compat.js", "members.js", "command.js", "tools.js"]
const DERIVED = ["mpd-deltas.js"] // regenerated by --write-registry; --check asserts its regions
const files = readdirSync(libDir).filter((name) => name.endsWith(".js"))
let violations = 0
let deletions = 0
for (const file of files.sort()) {
    let head
    try {
        head = execFileSync("git", ["show", `HEAD:packages/mpd-agent-teams-plugin/lib/${file}`], { cwd: repoRoot, encoding: "utf8" })
    }
    catch {
        console.log(`=== ${file}: NEW FILE (no committed twin)`)
        continue
    }
    const before = stripRegions(head)
    const after = stripRegions(readFileSync(join(libDir, file), "utf8"))
    if (before === after) {
        console.log(`=== ${file}: region-less projection IDENTICAL to HEAD`)
        continue
    }
    if (DERIVED.includes(file)) {
        console.log(`=== ${file}: DERIVED registry regenerated by --write-registry (not an adopted file; --check asserts region fidelity)`)
        continue
    }
    const beforePath = join(outDir, `${file}.head`)
    const afterPath = join(outDir, `${file}.work`)
    writeFileSync(beforePath, before)
    writeFileSync(afterPath, after)
    let diff = ""
    try {
        diff = execFileSync("git", ["diff", "--no-index", "-U0", beforePath, afterPath], { cwd: repoRoot, encoding: "utf8" })
    }
    catch (error) {
        diff = String(error.stdout ?? "")
    }
    const added = diff.split("\n").filter((line) => line.startsWith("+") && !line.startsWith("+++"))
    const removed = diff.split("\n").filter((line) => line.startsWith("-") && !line.startsWith("---"))
    deletions += removed.length
    const bridged = BRIDGED.includes(file)
    console.log(`=== ${file}: ${removed.length} line(s) removed, ${added.length} line(s) added outside regions${bridged ? " (bridged file: removals expected)" : " (EDIT-FREE file: any change is a violation)"}`)
    for (const line of added) console.log(`  VIOLATION +${line.slice(1)}`)
    if (added.length > 0 || !bridged) violations += added.length + (bridged ? 0 : removed.length)
    for (const line of removed) console.log(`  -${line.slice(1)}`)
}
console.log(`\ntotal lines removed outside regions: ${deletions}; violations: ${violations}`)
process.exit(violations === 0 ? 0 : 1)
