import { readFileSync, writeFileSync } from "node:fs"

const data = JSON.parse(readFileSync("evidence/omo-align/interjection-tools/raw/reachability-inventory.json", "utf8"))
const bySymbol = new Map(data.rows.map((row) => [row.symbol, row]))

// The symbols this wave created or changed, plus every export the scan found unreferenced.
const TRACKED = [
  "appendMailboxDeduped", "expireInterjections", "expireInterjectionsEverywhere",
  "enqueueInterjection", "decideInterjection", "clearMailboxToWatermark",
  "readLiveMailbox", "readInterjections", "readPendingInterjections",
  "readRawInterjectionRecords", "messageDedupKey", "deliverableUnread", "isTaskReady",
  "installInterjectionExpirySweep", "installSessionTeamPolicy",
  "INTERJECTION_KIND", "INTERJECTION_QUEUE", "INTERJECTION_TTL_MS", "MAILBOX_DEDUP_WINDOW_MS",
]

const line = (row) => {
  if (row === undefined) return undefined
  const where = row.className === "NO PRODUCTION CALLER"
    ? "**NO PRODUCTION CALLER**"
    : row.className.includes("cross-module") ? "reachable (cross-module)" : "reachable (module-internal)"
  return `| \`${row.symbol}\` | \`${row.declared}\` | ${where} | ${row.firstUse === undefined ? "—" : `\`${row.firstUse}\``} |`
}

const unreferenced = data.rows.filter((row) => row.className === "NO PRODUCTION CALLER")

const md = `# Production-path reachability inventory (t52)

Generated by \`raw/reachability-inventory.mjs\` from the shipped \`lib/**\` sources.
Machine-readable form: \`raw/reachability-inventory.json\`.

**Why this exists.** This wave's recurring defect class was "written, unit-tested, never
called on the path a user walks" (F-1 for the dedup fold, F-4 for the whole interjection
lane). A green primitive test proved nothing. This is the sweep that makes that class
visible on demand, and it is the first thing to re-run after any capability change.

## Summary

| Measure | Count |
|---|---|
| exports declared in \`lib/**\` (registry excluded) | ${data.summary.totalExports} |
| reachable cross-module | ${data.summary.crossModule} |
| reachable module-internally | ${data.summary.moduleInternal} |
| **no production caller** | **${unreferenced.length}** |

## The lane this task wired

| Export | Declared | Production reachability | First production use |
|---|---|---|---|
${TRACKED.map((symbol) => line(bySymbol.get(symbol))).filter(Boolean).join("\n")}

## Every export with NO production caller (${unreferenced.length})

| Export | Declared | Decision |
|---|---|---|
${unreferenced.map((row) => {
  if (row.symbol === "readLiveMailbox") {
    return `| \`readLiveMailbox\` | \`${row.declared}\` | **KEPT, documented as test-only** (t52). No production caller and none should appear: the scheduler composes \`deliverableUnread(readUnreadMailbox(...))\`, where the tombstone filter is carried independently by BOTH functions, so routing through this one would drop the delivery-lease semantics. Kept because it states the F-3 invariant in one expression and the seam tests assert it directly. The doc comment now says all of this at the declaration. |`
  }
  if (row.symbol === "teamLockQueueKeys") {
    return `| \`teamLockQueueKeys\` | \`${row.declared}\` | **KEPT, diagnostic/test-only.** A lock-queue snapshot used by \`test/backports.test.ts\` to assert that a completed \`withTeamLock\` leaves NO queued key (a lock-leak check). Its own doc comment already says "for diagnostics and leak checks". Nothing in production may call it: it exposes internal lock state. |`
  }
  if (row.symbol === "SESSION_START_GATE_ID") {
    return `| \`SESSION_START_GATE_ID\` | \`${row.declared}\` | **PRE-EXISTING orphan — reported, not deleted.** Present in HEAD before this task, referenced by nothing in \`lib/**\`, \`test/**\` or \`skills/**\`. It is a frozen diagnostic identifier, not a capability, so deleting it would be unrelated churn in a file this task is trying to keep stable; it is listed here so the next capability sweep does not have to rediscover it. |`
  }
  return `| \`${row.symbol}\` | \`${row.declared}\` | UNCLASSIFIED — needs a decision |`
}).join("\n")}

## How to read a "reachable (module-internal)" row

\`deliverableUnread\` and \`isTaskReady\` are module-private by construction (they are not
exported for other modules and are called by \`nextReadyTask\` / the two scheduler reads).
That is not the F-1 defect: the defect is an exported capability with no consumer at all,
which is what the three rows above are.
`

writeFileSync("evidence/omo-align/interjection-tools/reachability.md", md)
console.log(JSON.stringify({ written: "evidence/omo-align/interjection-tools/reachability.md", tracked: TRACKED.length, unreferenced: unreferenced.map((r) => r.symbol) }, null, 1))
