#!/usr/bin/env node
// gen-roles: convert the OMO-origin standalone presets (packages/mpd-presets-plugin/presets/<id>)
// into the subagent ROSTER consumed by mpd-roles-plugin:
//   - packages/mpd-roles-plugin/personas/<id>.md      persona text (from the preset's dsh-persona row)
//   - packages/mpd-roles-plugin/src/roles.data.ts     id/name/description/readonly/chain/personaFile
// One-time migration generator (the preset dirs are deleted afterwards); inputs are the
// pre-migration preset tree. Run: node scripts/gen-roles.mjs
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const presetsDir = join(repoRoot, "packages", "mpd-presets-plugin", "presets")
const outData = join(repoRoot, "packages", "mpd-roles-plugin", "src", "roles.data.ts")
const outPersonas = join(repoRoot, "packages", "mpd-roles-plugin", "personas")

// Per-role information that has no home inside the preset files.
const READONLY = new Set(["oracle", "librarian", "prometheus", "momus", "explore", "multimodal-looker"])
const CHAIN_KEYS = {
  sisyphus: "sisyphus",
  "sisyphus-junior": "sisyphusJunior",
  oracle: "oracle",
  atlas: "atlas",
  prometheus: "prometheus",
  librarian: "librarian",
  explore: "explore",
  metis: "metis",
  momus: "momus",
  "multimodal-looker": "multimodalLooker",
  hephaestus: "hephaestus",
}
// Source of truth for chains at generation time: mpd-modelchain DEFAULT_CHAINS.
const CHAIN_SOURCE = join(repoRoot, "packages", "mpd-modelchain-plugin", "src", "index.ts")

function fail(msg) { console.error("[gen-roles] FAIL - " + msg); process.exit(1) }

function readChains() {
  const src = readFileSync(CHAIN_SOURCE, "utf8")
  const m = src.match(/export const DEFAULT_CHAINS[\s\S]*?=\s*\{([\s\S]*?)\n\}/)
  if (!m) fail("DEFAULT_CHAINS not found in " + CHAIN_SOURCE)
  const chains = {}
  const re = /^\s{2}([A-Za-z]+):\s*\[([\s\S]*?)\]/gm
  let hit
  while ((hit = re.exec(m[1]))) {
    const entries = []
    const ere = /\{\s*provider:\s*"([^"]+)",\s*model:\s*"([^"]+)"\s*\}/g
    let e
    while ((e = ere.exec(hit[2]))) entries.push({ provider: e[1], model: e[2] })
    if (entries.length) chains[hit[1]] = entries
  }
  if (Object.keys(chains).length === 0) fail("no chains parsed from DEFAULT_CHAINS")
  return chains
}

function extractPersona(agentCordis) {
  const lines = agentCordis.split("\n")
  let inPersona = false
  let inText = false
  const out = []
  for (const line of lines) {
    if (/^-\s+id:\s*persona\s*$/.test(line)) { inPersona = true; continue }
    if (inPersona && /^-\s+id:/.test(line)) break
    if (!inPersona) continue
    if (/^\s*config:/.test(line)) continue
    if (/^\s*text:\s*(>-|\|)\s*$/.test(line.trim())) { inText = true; continue }
    if (inText) {
      if (/^\S/.test(line)) break // back to a new top-level row
      out.push(line)
    }
  }
  if (out.length === 0) fail("persona text not extracted from agent.cordis.yml")
  const nonBlank = out.filter((l) => l.trim() !== "")
  const base = Math.min(...nonBlank.map((l) => l.match(/^ */)[0].length))
  return out.map((l) => (l.trim() === "" ? "" : l.slice(base)))
    .join("\n").replace(/^\n+|\s+$/g, "") + "\n"
}

const chains = readChains()
const roles = []
for (const dir of ["mpd-oracle", "mpd-librarian", "mpd-prometheus", "mpd-hephaestus", "mpd-sisyphus", "mpd-atlas", "mpd-explore", "mpd-metis", "mpd-momus", "mpd-multimodal-looker", "mpd-sisyphus-junior"]) {
  const base = join(presetsDir, dir)
  if (!existsSync(base)) fail("preset dir missing: " + dir)
  const id = dir.replace(/^mpd-/, "")
  const meta = readFileSync(join(base, "preset.yml"), "utf8")
  const nameM = meta.match(/^name:\s*"?([^"\n]+)"?\s*$/m)
  const descM = meta.match(/^description:\s*"?([^"\n]+)"?\s*$/m)
  if (!nameM || !descM) fail("preset.yml metadata missing for " + dir)
  const chainKey = CHAIN_KEYS[id]
  if (!chainKey || !chains[chainKey]) fail("no chain for role " + id)
  roles.push({
    id,
    name: nameM[1].trim().replace(/^MPD\s+/i, "").replace(/"$/, ""),
    description: descM[1].trim().replace(/"$/, ""),
    readonly: READONLY.has(id),
    chain: chains[chainKey],
  })
}

mkdirSync(outPersonas, { recursive: true })
const specs = []
for (const r of roles) {
  const agent = readFileSync(join(presetsDir, "mpd-" + r.id, "agent.cordis.yml"), "utf8")
  const persona = extractPersona(agent)
  writeFileSync(join(outPersonas, r.id + ".md"), persona)
  specs.push({ ...r, personaFile: "personas/" + r.id + ".md" })
}

let data = `// GENERATED by scripts/gen-roles.mjs — the OMO-origin agent roster (subagent definitions).
// Do not edit by hand: regenerate with \`node scripts/gen-roles.mjs\` after a persona/
// chain change. Main consumer surfaces: mpd_roles_list / mpd_role_spawn /
// mpd_role_persona (specialist spawn) and mpd_modelchain_resolve (chain lookup).
export interface MpdRoleSpec {
  id: string
  name: string
  description: string
  /** Read-only roles spawn with a write-tool deny filter; workers spawn unrestricted. */
  readonly: boolean
  chain: Array<{ provider: string; model: string }>
  personaFile: string
}

export const ROLES: MpdRoleSpec[] = [
`
data += specs.map((r) => "  " + JSON.stringify(r, null, 2).split("\n").join("\n  ")).join(",\n")
data += `\n]

export const ROLE_BY_ID: Record<string, MpdRoleSpec> = Object.fromEntries(ROLES.map((r) => [r.id, r]))
`
writeFileSync(outData, data)
console.log("[gen-roles] wrote " + roles.length + " roles -> " + outData)
console.log("[gen-roles] PASS")