#!/usr/bin/env node
// Installer for a pre-commit guard on the skills/** corpus re-pin (friction item T-34).
//
// WHY: every `skills/**` change invalidates the corpus `treeSha` in VENDOR_LOCK.json, and the
// re-pin must land in the SAME commit as the change that invalidated it (AGENTS.md §9/§11, the
// single-skills-writer rule). This guard REFUSES a commit that stages a corpus change without the
// lock, and names the exact remedy sequence.
//
// INVARIANT: the hook can never re-pin. `scripts/repin-vendor.ts --write` refuses the repository's
// own VENDOR_LOCK.json unless `--i-know-this-is-the-captains-step` is also passed, so a wave cannot
// re-pin mid-flight; a hook that ran the re-pin on the caller's behalf would defeat that refusal
// while looking like a guard. This hook therefore refuses only - it never runs the re-pin and never
// passes the marker for anyone. The marker stays the captain's explicit step.
//
// SHAPE: the hook text is CARRIED by this installer and written to <hooks-dir>/pre-commit (mode
// 0755). No tracked hook file exists in the repository (`.githooks/**` is deliberately not used).
//
// USAGE: node scripts/install-git-hooks.ts [--hooks-dir <dir>] [--force] [--self-test]
//   (default)        install to the repository's real .git/hooks
//   --hooks-dir <d>  install elsewhere (QA / temp use)
//   --force          overwrite an existing pre-commit hook (default: refuse, non-zero, write nothing)
//   --self-test      every arm in a throwaway repo; NEVER writes the real .git/hooks
import { spawnSync } from "node:child_process"
import { createHash } from "node:crypto"
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { delimiter, dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import type { SpawnSyncReturns } from "node:child_process"

/** This script's own path, from which the repository root is derived two levels up. */
const SELF: string = fileURLToPath(import.meta.url)
/** The repository root: `<root>/scripts/install-git-hooks.ts` is where this file lives. */
const REPO_ROOT: string = dirname(dirname(SELF))
/** The line prefix every message of this installer carries, so its output stays greppable. */
const TAG: string = "[install-git-hooks]"
/** The single hook file name this installer owns; git only runs a hook with exactly this name. */
const HOOK_NAME: string = "pre-commit"
/** The lock file whose staging decides whether a corpus change may be committed. */
const LOCK_NAME: string = "VENDOR_LOCK.json"
/** The staged-path prefix that marks a commit as touching the vendored skill corpus. */
const CORPUS_PREFIX: string = "skills/"
/** The marker that makes `repin-vendor.ts --write` legal for this repository's own lock file. */
const MARKER: string = "--i-know-this-is-the-captains-step"
// The single source of the remedy: the hook's refusal text and the self-test assertions both read it.
const REMEDY: readonly string[] = [
  "node scripts/repin-vendor.ts --check",
  `node scripts/repin-vendor.ts --write ${MARKER}`,
  "node scripts/verify-vendor.ts",
]
/** The `--help` text: the usage line plus one line per mode and flag this installer accepts. */
const USAGE: string = [
  "usage: node scripts/install-git-hooks.ts [--hooks-dir <dir>] [--force] [--self-test]",
  "  (no mode)        install <hooks-dir>/pre-commit (default: this repository's real .git/hooks)",
  "  --hooks-dir <d>  install into <d> instead of the real .git/hooks",
  "  --force          overwrite an existing pre-commit hook (default refuses and writes nothing)",
  "  --self-test      run every arm in throwaway repos; never touches the real .git/hooks",
].join("\n")

/** A refusal is a loud, non-mutating abort: this helper never guesses where a hook belongs. */
class Refusal extends Error {}

/** Every path this process installed into; arm (e) proves the real .git/hooks is never among them. */
const installedTargets: string[] = []

// ---------------------------------------------------------------------------------------------
// The hook text (POSIX sh, carried here and written out by installHook)
// ---------------------------------------------------------------------------------------------

/** The generated pre-commit hook: POSIX sh, refuses a staged corpus change with no staged re-pin. */
function renderHook(): string {
  return `#!/bin/sh
# Generated by scripts/install-git-hooks.ts - pre-commit guard for the skills/** corpus re-pin.
# A staged skills/** change must carry its VENDOR_LOCK.json re-pin in the SAME commit
# (AGENTS.md 9/11: ONE corpus writer, ONE re-pin). This guard REFUSES; it NEVER re-pins, and it
# never passes --i-know-this-is-the-captains-step for the caller - that marker is the captain's step.
set -u
TAG='${TAG}'
LOCK='${LOCK_NAME}'

if ! command -v git >/dev/null 2>&1; then
  echo "$TAG REFUSED: git is not on PATH, so the staged change set cannot be checked." >&2
  echo "$TAG this guard never skips silently; install git, or pass --no-verify deliberately." >&2
  exit 1
fi

staged=$(git -c core.quotePath=false diff --cached --name-only 2>&1)
status=$?
if [ "$status" -ne 0 ]; then
  echo "$TAG REFUSED: git diff --cached --name-only failed (exit $status); staged set unknown." >&2
  echo "$TAG git said: $staged" >&2
  exit 1
fi

corpus=$(printf '%s\\n' "$staged" | grep -c '^${CORPUS_PREFIX}')
lock_staged=$(printf '%s\\n' "$staged" | grep -c -F -x "$LOCK")
if [ "$corpus" -eq 0 ] || [ "$lock_staged" -gt 0 ]; then
  exit 0
fi

echo "$TAG REFUSED: staged ${CORPUS_PREFIX}** change without a staged $LOCK re-pin - remedy: ${REMEDY[0]}; ${REMEDY[1]}; ${REMEDY[2]}"
echo "$TAG REFUSED: staged ${CORPUS_PREFIX}** change without a staged $LOCK re-pin." >&2
echo "$TAG corpus path(s) staged without the lock:" >&2
printf '%s\\n' "$staged" | grep '^${CORPUS_PREFIX}' | sed "s|^|$TAG   - |" >&2
echo "$TAG remedy - run these from the repository root, in this order, then commit:" >&2
echo "$TAG   1) ${REMEDY[0]}" >&2
echo "$TAG   2) ${REMEDY[1]}" >&2
echo "$TAG   3) ${REMEDY[2]}" >&2
echo "$TAG the --write marker stays the captain's explicit step; this guard never passes it." >&2
exit 1
`
}

/**
 * Health check on a generated hook's TEXT. Arm (d) proves it is falsifiable (empty / unwired text
 * reddens), because behaviour alone cannot: an empty hook exits 0 and looks like a green commit.
 */
function inspectHook(text: string): string[] {
  // `problems` collects every way the text fails to be a wired guard, so a caller can print them all.
  const problems: string[] = []
  if (text.trim() === "") problems.push("generated hook is empty")
  if (!text.startsWith("#!/bin/sh")) problems.push("generated hook has no #!/bin/sh shebang (unwired)")
  if (!text.includes("git diff --cached --name-only")) problems.push("generated hook never reads the staged change set (unwired)")
  if (!/exit 1/.test(text)) problems.push("generated hook has no non-zero exit path")
  // Every remedy step has to be named, or the refusal cannot tell the reader what to run.
  for (const step of REMEDY) if (!text.includes(step)) problems.push(`generated hook does not name a remedy step: ${step}`)
  if (text.includes("--write") && !text.includes(MARKER)) problems.push("generated hook mentions --write without the captain marker")
  return problems
}

// ---------------------------------------------------------------------------------------------
// Install + filesystem helpers
// ---------------------------------------------------------------------------------------------

/** The options `installHook` honours, as parsed from the CLI or set by a self-test arm. */
interface InstallOptions {
  /** When true an existing hook is overwritten; when false it is refused and nothing is written. */
  readonly force: boolean
}

/** A completed install: the path written and the hash of the bytes that are on disk now. */
interface InstallResult {
  /** Absolute path of the hook file that was written. */
  readonly target: string
  /** sha256 (hex) of the file's bytes AFTER the write, as printed on the install lines. */
  readonly sha256: string
}

/** Write the guard into hooksDir. Refuses an existing hook unless force; prints path + sha256. */
function installHook(hooksDir: string, { force }: InstallOptions): InstallResult {
  // `target` is the hook path this install would occupy, and the path every refusal names.
  const target: string = join(hooksDir, HOOK_NAME)
  if (existsSync(target) && !force) {
    throw new Refusal(`${target} already exists - pass --force to overwrite it (nothing was written)`)
  }
  mkdirSync(hooksDir, { recursive: true })
  writeFileSync(target, renderHook(), { encoding: "utf8", mode: 0o755 })
  chmodSync(target, 0o755)
  // `bytes` is the hook as it lies on disk, so the hash describes the file rather than the string.
  const bytes = readFileSync(target)
  // `sha256` is the hex digest printed for the caller to compare against a later snapshot.
  const sha256: string = createHash("sha256").update(bytes).digest("hex")
  installedTargets.push(target)
  console.log(`${TAG} installed: ${target}`)
  console.log(`${TAG} mode: 0755  bytes: ${bytes.length}  sha256: ${sha256}`)
  return { target, sha256 }
}

/** sha256 (hex) of one file's bytes, used by every byte-identity assertion in the self-test. */
function sha256File(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex")
}

/**
 * File identity used to prove a file was NOT rewritten: content hash + mtime for a path that
 * exists, or the all-null missing state. `exists` is a literal discriminator, so a reader narrows
 * to the branch carrying the hash instead of re-checking the two nulls.
 */
type FileSnapshot =
  | {
      /** False when the path did not exist at sampling time. */
      readonly exists: false
      /** Always null in the missing state, so the shape stays uniform across both branches. */
      readonly sha256: null
      /** Always null in the missing state, so the shape stays uniform across both branches. */
      readonly mtimeMs: null
    }
  | {
      /** True when the path existed at sampling time. */
      readonly exists: true
      /** sha256 (hex) of the file's bytes as sampled. */
      readonly sha256: string
      /** Last-modification time in milliseconds since the epoch. */
      readonly mtimeMs: number
    }

/** File identity used to prove a file was NOT rewritten: content hash + mtime, or a missing state. */
function snapshot(path: string): FileSnapshot {
  if (!existsSync(path)) return { exists: false, sha256: null, mtimeMs: null }
  // `st` is the stat record the mtime is read from, sampled in the same breath as the hash.
  const st = statSync(path)
  return { exists: true, sha256: sha256File(path), mtimeMs: st.mtimeMs }
}

/** Where this run installs, plus the rule that resolved it — both are printed on the install lines. */
interface HooksLocation {
  /** Absolute path of the resolved hooks directory. */
  readonly dir: string
  /** How the path was resolved: `--hooks-dir`, `git rev-parse`, or the repository fallback. */
  readonly via: string
}

/** Resolve the repository's real hooks directory through git, falling back to `<repo>/.git/hooks`. */
function resolveRealHooksDir(): HooksLocation {
  // `probe` asks git itself, so a worktree or a custom core.hooksPath is honoured rather than assumed.
  const probe = spawnSync("git", ["rev-parse", "--git-path", "hooks"], { cwd: REPO_ROOT, encoding: "utf8" })
  // `out` is git's answer, or empty when git failed and the repository fallback below has to be used.
  const out: string = probe.status === 0 ? probe.stdout.trim() : ""
  if (out === "") return { dir: join(REPO_ROOT, ".git", "hooks"), via: "fallback <repo>/.git/hooks" }
  return { dir: out.startsWith("/") ? out : join(REPO_ROOT, out), via: "git rev-parse --git-path hooks" }
}

/** Run one git command in `cwd` and hand back the raw synchronously captured result. */
function git(cwd: string, args: readonly string[]): SpawnSyncReturns<string> {
  return spawnSync("git", args, { cwd, encoding: "utf8" })
}

/**
 * Assert an invariant of this run: on failure the message is thrown as a {@link Refusal}, which the
 * CLI prints as `REFUSED:` and maps to exit 1. The `asserts` signature is ERASED at runtime (Node
 * type stripping removes it), and it lets a caller narrow a value without an otherwise-unneeded cast.
 */
function must(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Refusal(message)
}

/**
 * The shell a Git hook is written for, when this host cannot execute the hook file itself.
 *
 * A Git hook is a POSIX shell script BY CONTRACT: Git for Windows runs it with a `sh.exe` it
 * ships, and a direct spawn of the file answers ENOENT there. Measured 2026-09-22: four arms
 * below failed on win32 with `spawnSync ...\\pre-commit ENOENT` while the hook on disk was
 * exactly right. POSIX answers null: the file stays executable as-is.
 */
function hookShell(): string | null {
  if (process.platform !== "win32") return null
  // `bundled` is each standard Git-for-Windows `sh.exe` location, checked before PATH is consulted.
  for (const bundled of [
    "C:\\Program Files\\Git\\bin\\sh.exe",
    "C:\\Program Files (x86)\\Git\\bin\\sh.exe",
    "C:\\Program Files\\Git\\usr\\bin\\sh.exe",
  ]) {
    if (existsSync(bundled)) return bundled
  }
  // `suffixes` is every executable form Windows may append to a bare `sh` name, longest first.
  const suffixes: readonly string[] = [".exe", ".cmd", ".bat", ".com", ""]
  // `dir` is each PATH entry; an empty entry means the current directory and is skipped.
  for (const dir of String(process.env.PATH ?? "").split(delimiter)) {
    if (dir.length === 0) continue
    // `suffix` is one candidate executable extension for this PATH entry.
    for (const suffix of suffixes) {
      // `candidate` is the concrete `sh<suffix>` path probed with existsSync.
      const candidate: string = join(dir, "sh" + suffix)
      if (existsSync(candidate)) return candidate
    }
  }
  return null
}

/** A hook execution's observable result: exit status (null when it never ran) plus both streams. */
interface HookRun {
  /** The hook's exit status, or null when it was killed by a signal instead of exiting. */
  readonly code: number | null
  /** stdout and stderr concatenated in that order, which is how the arms' assertions read them. */
  readonly out: string
  /** The hook's raw stdout, kept separately for a caller that needs one stream only. */
  readonly stdout: string
  /** The hook's raw stderr, kept separately for a caller that needs one stream only. */
  readonly stderr: string
}

/** Run the installed hook exactly as git would: the file itself, executable, cwd = repo root. */
function runHook(hookPath: string, cwd: string): HookRun {
  // `shell` is the interpreter to borrow on a host that cannot exec the hook file directly.
  const shell: string | null = hookShell()
  if (shell === null && process.platform === "win32") {
    must(false, `no sh to run a Git hook with: install Git for Windows (or put its bin dir on PATH) and rerun --self-test (${hookPath})`)
  }
  // `result` is the captured hook run: the file itself on POSIX, or `sh <hook>` where that is needed.
  const result: SpawnSyncReturns<string> =
    shell === null ? spawnSync(hookPath, [], { cwd, encoding: "utf8" }) : spawnSync(shell, [hookPath], { cwd, encoding: "utf8" })
  must(result.status !== null || result.error === undefined, `hook could not be executed: ${result.error?.message ?? "unknown"}`)
  return { code: result.status, out: `${result.stdout ?? ""}${result.stderr ?? ""}`, stdout: result.stdout ?? "", stderr: result.stderr ?? "" }
}

// ---------------------------------------------------------------------------------------------
// Self-test: every arm in a throwaway repo, never the real .git/hooks
// ---------------------------------------------------------------------------------------------

/** A throwaway git repository the self-test arms stage their fixture changes in. */
interface FixtureRepo {
  /** Absolute path of the throwaway repository root (removed by the arm's `finally`). */
  readonly root: string
  /** The throwaway repository's own `.git/hooks` directory, where the guard is installed. */
  readonly hooksDir: string
  /** Absolute path of the fixture `VENDOR_LOCK.json` whose bytes the arms watch. */
  readonly lockPath: string
}

/** Create a committed throwaway repository holding the corpus, a source file and the lock file. */
function makeRepo(label: string, gitOk: boolean): FixtureRepo {
  must(gitOk, "git is not available on PATH - the corpus guard cannot be exercised")
  // `root` is the fresh temp repository, named by arm label so a leftover dir names its arm.
  const root: string = mkdtempSync(join(tmpdir(), `install-git-hooks-${label}-`))
  mkdirSync(join(root, "skills", "dsh-qa"), { recursive: true })
  mkdirSync(join(root, "src"), { recursive: true })
  writeFileSync(join(root, "skills", "dsh-qa", "SKILL.md"), "baseline corpus file\n")
  writeFileSync(join(root, "src", "app.js"), "export const baseline = 1\n")
  writeFileSync(join(root, LOCK_NAME), `${JSON.stringify({ corpus: { treeSha: "baseline" } }, null, 2)}\n`)
  must(git(root, ["init", "-q"]).status === 0, "throwaway repo: git init failed")
  git(root, ["config", "user.email", "self-test@install-git-hooks.invalid"])
  git(root, ["config", "user.name", "install-git-hooks self-test"])
  must(git(root, ["add", "-A"]).status === 0, "throwaway repo: git add failed")
  // `commit` is the baseline commit every arm starts from; its stderr is named when it fails.
  const commit = git(root, ["-c", "commit.gpgsign=false", "commit", "-q", "-m", "baseline"])
  must(commit.status === 0, `throwaway repo: baseline commit failed (${commit.stderr.trim()})`)
  return { root, hooksDir: join(root, ".git", "hooks"), lockPath: join(root, LOCK_NAME) }
}

/** The knobs one corpus arm sets before it stages its fixture change. */
interface CorpusArmOptions {
  /** Whether the arm also stages the re-pinned VENDOR_LOCK.json beside the corpus change. */
  readonly withLock: boolean
  /** Whether git is usable on this host; false fails the arm loudly instead of skipping it. */
  readonly gitOk: boolean
}

/** One corpus arm's outcome: the hook's verdict plus the lock identity it must preserve. */
interface CorpusArmResult {
  /** The installed hook's own run result, which the arm asserts an exit code and remedy text on. */
  readonly verdict: HookRun
  /** sha256 of the fixture lock AFTER the hook ran (must equal the hash taken just before it ran). */
  readonly lockSha: string
  /** Whether that post-run hash still matches the committed baseline the fixture started from. */
  readonly pristineUnchanged: boolean
}

/**
 * Stage a corpus tweak and return the hook's verdict. The invariant this asserts is that the HOOK
 * is read-only over the lock: whatever the caller staged (nothing, or the re-pin) is byte-identical
 * after the hook ran, so the guard can never re-pin on its own.
 */
function runCorpusArm(label: string, { withLock, gitOk }: CorpusArmOptions): CorpusArmResult {
  // `repo` is the throwaway repository this arm owns, removed in the `finally` below.
  const repo: FixtureRepo = makeRepo(label, gitOk)
  try {
    // `pristine` is the committed lock's hash, the reference the post-hook hash is compared against.
    const pristine: string = sha256File(repo.lockPath)
    installHook(repo.hooksDir, { force: false })
    writeFileSync(join(repo.root, "skills", "dsh-qa", "SKILL.md"), "baseline corpus file\ntweaked\n")
    // `staged` is the fixture path list handed to `git add`; the lock joins it only when asked for.
    const staged: string[] = ["skills/dsh-qa/SKILL.md"]
    if (withLock) {
      writeFileSync(repo.lockPath, `${JSON.stringify({ corpus: { treeSha: "re-pinned" } }, null, 2)}\n`)
      staged.push(LOCK_NAME)
    }
    must(git(repo.root, ["add", ...staged]).status === 0, "could not stage the fixture paths")
    // `stagedLockSha` is the lock's hash as staged, taken immediately before the hook can touch it.
    const stagedLockSha: string = sha256File(repo.lockPath)
    // `verdict` is the hook's own run, the thing every corpus arm asserts on.
    const verdict: HookRun = runHook(join(repo.hooksDir, HOOK_NAME), repo.root)
    // `afterHookSha` is the same file's hash after the hook ran; equality is the read-only proof.
    const afterHookSha: string = sha256File(repo.lockPath)
    must(stagedLockSha === afterHookSha, `the hook rewrote ${LOCK_NAME} (sha256 ${stagedLockSha} -> ${afterHookSha})`)
    return { verdict, lockSha: afterHookSha, pristineUnchanged: afterHookSha === pristine }
  } finally {
    rmSync(repo.root, { recursive: true, force: true })
  }
}

/** One self-test arm's outcome: PASS carries its evidence sentence, FAIL carries its refusal. */
interface ArmOutcome {
  /** The arm's stable name, printed on its census line. */
  readonly name: string
  /** Whether every assertion in the arm held. */
  readonly status: "PASS" | "FAIL"
  /** The arm's evidence sentence, present on PASS (what actually held). */
  readonly detail?: string
  /** The assertion message that failed the arm, present on FAIL. */
  readonly reason?: string
}

/** Run every self-test arm in throwaway repositories; returns 0 when all arms pass, else 1. */
function runSelfTest(): number {
  // `arms` collects each arm's outcome in run order, which is the order the census prints them in.
  const arms: ArmOutcome[] = []
  /** Record one arm's outcome without letting its failure escape the census. */
  const arm = (name: string, fn: () => string): void => {
    try {
      arms.push({ name, status: "PASS", detail: fn() })
    } catch (e) {
      arms.push({ name, status: "FAIL", reason: e instanceof Error ? e.message : String(e) })
    }
  }

  // `real` is the repository's real hooks location, resolved but never written by the self-test.
  const real: HooksLocation = resolveRealHooksDir()
  // `realPreCommit` is the real pre-commit path whose bytes arm (e) proves unchanged.
  const realPreCommit: string = join(real.dir, HOOK_NAME)
  // `realBefore` is that file's identity before any arm ran.
  const realBefore: FileSnapshot = snapshot(realPreCommit)
  // `gitProbe` answers whether git exists at all; without it no arm can stage anything.
  const gitProbe = spawnSync("git", ["--version"], { encoding: "utf8" })
  // `gitOk` is the arms' single gate on git availability, and is reported on the header lines.
  const gitOk: boolean = gitProbe.status === 0
  console.log(`${TAG} self-test roots: throwaway repos under ${tmpdir()}`)
  console.log(`${TAG} real hooks dir (read-only snapshot): ${realPreCommit} (${real.via})`)
  console.log(`${TAG} git: ${gitOk ? gitProbe.stdout.trim() : `UNAVAILABLE (${gitProbe.error?.message ?? "spawn failed"})`}`)

  // (a) corpus tweak staged WITHOUT the lock -> refused, remedy named, lock byte-unchanged.
  arm("a-corpus-without-lock-refused", (): string => {
    // `verdict`, `lockSha` and `pristineUnchanged` are the arm's whole subject: what the hook said
    // and whether the lock it must never touch still matches the commit it started from.
    const { verdict, lockSha, pristineUnchanged } = runCorpusArm("a", { withLock: false, gitOk })
    must(verdict.code !== 0, `hook exited ${verdict.code} for a corpus change without the lock (expected non-zero)`)
    must(verdict.out.includes("REFUSED"), "refusal output does not say REFUSED")
    // Each remedy step is asserted separately so a missing one names the step it lost.
    for (const step of REMEDY) must(verdict.out.includes(step), `refusal output does not name the remedy step: ${step}`)
    must(pristineUnchanged, `${LOCK_NAME} no longer matches the committed baseline after the refusal`)
    return `exit ${verdict.code}; remedy named (${REMEDY.length} steps); ${LOCK_NAME} byte-unchanged (sha256 ${lockSha.slice(0, 12)}...)`
  })

  // (b) the lock is staged alongside the corpus change -> the commit proceeds untouched.
  arm("b-corpus-with-lock-passes", (): string => {
    // `verdict` is the hook's run; with the lock staged it must be a clean exit 0.
    const { verdict } = runCorpusArm("b", { withLock: true, gitOk })
    must(verdict.code === 0, `hook exited ${verdict.code} with the lock staged (expected 0); output: ${verdict.out.trim()}`)
    return "exit 0 with skills/ + VENDOR_LOCK.json staged together"
  })

  // (c) a NON-corpus change -> exit 0. Includes a "skills"-named path outside skills/ (prefix, not substring).
  arm("c-non-corpus-passes", (): string => {
    // `repo` is this arm's throwaway repository, removed in the `finally` below.
    const repo: FixtureRepo = makeRepo("c", gitOk)
    try {
      installHook(repo.hooksDir, { force: false })
      writeFileSync(join(repo.root, "src", "app.js"), "export const baseline = 2\n")
      mkdirSync(join(repo.root, "docs"), { recursive: true })
      writeFileSync(join(repo.root, "docs", "skills-notes.md"), "not the corpus\n")
      must(git(repo.root, ["add", "src/app.js", "docs/skills-notes.md"]).status === 0, "could not stage the fixture paths")
      // `verdict` is the hook's run for a staged set that does not touch the corpus prefix.
      const verdict: HookRun = runHook(join(repo.hooksDir, HOOK_NAME), repo.root)
      must(verdict.code === 0, `hook exited ${verdict.code} for a non-corpus change (expected 0); output: ${verdict.out.trim()}`)
      return "exit 0 for src/app.js + docs/skills-notes.md (prefix match, not substring)"
    } finally {
      rmSync(repo.root, { recursive: true, force: true })
    }
  })

  // (d) negative control for the health check: empty / unwired text MUST redden, and the unwired
  // stub really does let a corpus commit through - which is why the text check has to exist.
  arm("d-empty-or-unwired-hook-detected", (): string => {
    must(inspectHook(renderHook()).length === 0, `the generated hook fails its own health check: ${inspectHook(renderHook()).join("; ")}`)
    // `candidates` pairs each deliberately unhealthy text with the label the assertion names.
    const candidates: ReadonlyArray<readonly [string, string]> = [
      ["empty", ""],
      ["unwired", "#!/bin/sh\nexit 0\n"],
    ]
    // `label` names the kind of bad text; `text` is the bad hook body itself.
    for (const [label, text] of candidates) {
      must(inspectHook(text).length > 0, `health check passed a deliberately ${label} hook (not falsifiable)`)
    }
    // `repo` is this arm's throwaway repository, removed in the `finally` below.
    const repo: FixtureRepo = makeRepo("d", gitOk)
    try {
      // `stub` is the unwired hook installed in place of the guard, to prove behaviour alone is blind.
      const stub: string = join(repo.hooksDir, HOOK_NAME)
      mkdirSync(repo.hooksDir, { recursive: true })
      writeFileSync(stub, "#!/bin/sh\nexit 0\n", { mode: 0o755 })
      writeFileSync(join(repo.root, "skills", "dsh-qa", "SKILL.md"), "baseline corpus file\ntweaked\n")
      must(git(repo.root, ["add", "skills/dsh-qa/SKILL.md"]).status === 0, "could not stage the fixture paths")
      // `verdict` is the stub's run: it must exit 0 on a corpus commit, which is the whole point.
      const verdict: HookRun = runHook(stub, repo.root)
      must(verdict.code === 0, "the unwired stub did not behave as the negative control requires")
      must(inspectHook(readFileSync(stub, "utf8")).length > 0, "health check passed the unwired stub on disk")
      return "empty + unwired text redden; the unwired stub exits 0 on a corpus commit, so text health is required"
    } finally {
      rmSync(repo.root, { recursive: true, force: true })
    }
  })

  // (e) the whole self-test left the real .git/hooks alone - and never installed into it.
  arm("e-real-hooks-untouched", (): string => {
    // `realAfter` is the real pre-commit's identity after every arm ran, to be compared with before.
    const realAfter: FileSnapshot = snapshot(realPreCommit)
    /** Render a snapshot for a failure message, distinguishing a missing file from a present one. */
    const state = (s: FileSnapshot): string => (s.exists ? `exists sha256 ${s.sha256.slice(0, 12)}... mtime ${s.mtimeMs}` : "missing")
    must(JSON.stringify(realBefore) === JSON.stringify(realAfter), `the real ${realPreCommit} changed during the self-test: ${state(realBefore)} -> ${state(realAfter)}`)
    // `trespass` is every install that landed on the real hook path; it must be empty.
    const trespass: string[] = installedTargets.filter((t: string): boolean => t === realPreCommit)
    must(trespass.length === 0, `the self-test installed into the real hooks dir: ${trespass.join(", ")}`)
    // `outside` is every install that landed outside the temp root; it must be empty too.
    const outside: string[] = installedTargets.filter((t: string): boolean => !t.startsWith(tmpdir()))
    must(outside.length === 0, `a self-test install landed outside ${tmpdir()}: ${outside.join(", ")}`)
    return `real hooks untouched (${state(realBefore)}); ${installedTargets.length} install(s), all under ${tmpdir()}`
  })

  // (f) the installer's own contract: an existing hook is refused (file byte-untouched) unless
  // --force, and the sha256 it prints is the one on disk.
  arm("f-overwrite-refused-without-force", (): string => {
    // `repo` is this arm's throwaway repository, removed in the `finally` below.
    const repo: FixtureRepo = makeRepo("f", gitOk)
    try {
      // `hookPath` is the existing hook the first install must refuse to overwrite.
      const hookPath: string = join(repo.hooksDir, HOOK_NAME)
      // `sentinel` is the pre-existing hook text; byte equality with it proves nothing was written.
      const sentinel: string = "#!/bin/sh\necho sentinel\nexit 0\n"
      mkdirSync(repo.hooksDir, { recursive: true })
      writeFileSync(hookPath, sentinel, { mode: 0o755 })
      // `refused` keeps whatever the install threw; the assertions below establish its class.
      let refused: unknown = null
      try {
        installHook(repo.hooksDir, { force: false })
      } catch (e) {
        refused = e
      }
      must(refused instanceof Refusal, "an existing hook was not refused without --force")
      must(refused.message.includes("--force"), "the refusal does not name --force")
      must(readFileSync(hookPath, "utf8") === sentinel, "the refused install still overwrote the existing hook")
      // `forced` is the second install, which may overwrite and prints the hash of what it wrote.
      const forced: InstallResult = installHook(repo.hooksDir, { force: true })
      must(forced.sha256 === sha256File(hookPath), "the printed sha256 does not match the file on disk")
      must(inspectHook(readFileSync(hookPath, "utf8")).length === 0, "the forced install left an unhealthy hook on disk")
      return `existing hook refused without --force (file byte-untouched); --force overwrote; sha256 ${forced.sha256.slice(0, 12)}... matches disk`
    } finally {
      rmSync(repo.root, { recursive: true, force: true })
    }
  })

  // `failed` counts the arms that reported FAIL, which decides the exit code and the census wording.
  const failed: number = arms.filter((a: ArmOutcome): boolean => a.status === "FAIL").length
  console.log(`${TAG} self-test census: ${arms.length} arm(s)`)
  // `a` is one arm's outcome, printed as its census line in run order.
  for (const a of arms) {
    console.log(a.status === "PASS" ? `${TAG} arm ${a.name}: PASS - ${a.detail}` : `${TAG} arm ${a.name}: FAIL - ${a.reason}`)
  }
  if (failed === 0) {
    console.log(`${TAG} self-test PASS: ${arms.length}/${arms.length} arms`)
    return 0
  }
  console.log(`${TAG} self-test FAIL: ${arms.length - failed}/${arms.length} arms`)
  return 1
}

// ---------------------------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------------------------

/** Parsed CLI options: where to install, whether to overwrite, and which mode to run. */
interface CliOptions {
  /** The explicit `--hooks-dir` target, or null to resolve the repository's own hooks directory. */
  hooksDir: string | null
  /** Whether `--force` was passed; an existing hook is otherwise refused and nothing is written. */
  force: boolean
  /** Whether `--self-test` was passed; every arm then runs in throwaway repos. */
  selfTest: boolean
}

/** Parse the CLI arguments and run the selected mode; returns the process exit code. */
function main(argv: readonly string[]): number {
  // `opts` is the parsed option set, mutated in place as each flag is read.
  const opts: CliOptions = { hooksDir: null, force: false, selfTest: false }
  // `i` walks the argv while `--hooks-dir`/`--member`-style flags consume the token after them.
  for (let i = 0; i < argv.length; i++) {
    // `arg` is the flag being read at this position.
    const arg: string = argv[i]
    if (arg === "--hooks-dir") {
      // `next` is the directory argument; a missing or flag-shaped value is refused, not guessed.
      const next: string | null = argv[++i] ?? null
      if (next === null || next.startsWith("--")) throw new Refusal("--hooks-dir needs a directory argument")
      opts.hooksDir = next
    } else if (arg === "--force") opts.force = true
    else if (arg === "--self-test") opts.selfTest = true
    else if (arg === "--help" || arg === "-h") {
      console.log(USAGE)
      return 0
    } else throw new Refusal(`unknown argument ${JSON.stringify(arg)}`)
  }
  if (opts.selfTest) {
    if (opts.hooksDir !== null) console.log(`${TAG} --self-test ignores --hooks-dir by design: every arm uses a throwaway dir`)
    return runSelfTest()
  }
  // `resolved` is the directory this run installs into, plus the rule that chose it.
  const resolved: HooksLocation = opts.hooksDir !== null ? { dir: opts.hooksDir, via: "--hooks-dir" } : resolveRealHooksDir()
  console.log(`${TAG} hooks dir: ${resolved.dir} (${resolved.via})`)
  installHook(resolved.dir, { force: opts.force })
  console.log(`${TAG} the guard refuses a staged ${CORPUS_PREFIX}** change without a staged ${LOCK_NAME}; it never re-pins`)
  return 0
}

try {
  process.exitCode = main(process.argv.slice(2))
} catch (e) {
  if (e instanceof Refusal) {
    console.log(`${TAG} REFUSED: ${e.message}`)
    process.exitCode = 1
  } else {
    throw e
  }
}
