#!/usr/bin/env node
// mpd-ext — the developer CLI of the MPD extension interface (row `mpd-ext`).
//
// It shares ONE validator with the runtime: the descriptor is loaded with the
// plugin's own `buildExtension()` (packages/mpd-ext-plugin/src/registry.ts), the
// same function apply-time discovery calls. A manifest this CLI accepts is a
// manifest the loader accepts — there is deliberately no second rule set here,
// because "documented here, enforced differently there" is how a contract rots.
//
// Commands
//   validate <dir|mpd-ext.json>   exit 0 when the extension loads, exit 1 with one
//                                 line per item otherwise (CI-safe)
//   scaffold <name> [--dir <path>] [--with-mcp]
//                                 COPY templates/mpd-extension and rewrite its
//                                 placeholder names; --with-mcp keeps the stdio MCP
//                                 server (without it the copy drops that kind)
//   list                          what this host would discover, plane by plane
//   --self-test                   the CLI's own checks (temp dirs only)
//   --validator                   which validator this run actually loaded, and from where
//
// WHERE THE VALIDATOR COMES FROM (T-51): the CLI resolves its validator in two steps, and
// never re-implements a rule.
//   1. the TypeScript SOURCES (packages/mpd-ext-plugin/src/*.ts) — a checkout under bun, so
//      no build step can make the CLI validate a stale copy of the rules;
//   2. the COMPILED entry `packages/mpd-ext-plugin/dist/validator.js` — a packed artifact.
//      The packer copies `dist/` only (never `src/`), and the shipped bundle
//      (`dist/index.js`) exports just the plugin surface, so `scripts/pack-mpd.ts` emits
//      this sidecar: the same compiled validator plus ONE `export { … }` line. Measured
//      before the fix: inside `dist/mpd-package/` every command died with `Cannot find
//      module '…/packages/mpd-ext-plugin/src/registry.ts'`.
// Step 2 is also what makes the packed CLI runnable under plain `node` (no TS loader).
//
// The `scaffold` template travels with the package too (`templates/mpd-extension`, T-35).
//
// Lives under scripts/ rather than skills/** on purpose: skills/** is
// VENDOR_LOCK-fingerprinted, and touching it would force a treeSha re-pin.
import { cpSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, extname, join, resolve, sep } from "node:path"
import { fileURLToPath } from "node:url"
import { spawnSync } from "node:child_process"
import { readJson } from "./lib/repo.ts"
// The four validator surfaces this run consumes, typed from the SOURCES the runtime itself uses, so a
// signature change in the plugin is a compile error here instead of a runtime surprise in a packed copy.
import type { BuildExtensionOptions, BuildExtensionResult, DiscoveryResult, ExtensionEntry, RejectedExtension } from "../packages/mpd-ext-plugin/src/registry.ts"
import type { DiscoverPlaneOptions } from "../packages/mpd-ext-plugin/src/manifest.ts"
import type { MPD_EXT_CONTRACT, MpdExtensionPlane, MpdExtLoadError } from "../packages/mpd-ext-plugin/src/sdk.ts"
import type { MpdRoleSpec } from "../packages/mpd-roles-plugin/src/roles.data.ts"

/** Absolute path of this CLI, from which the repository root is derived. */
const scriptPath: string = fileURLToPath(import.meta.url)
/** The repository root: this script lives at `<root>/scripts/`, so two levels up is the bundle root. */
const repoRoot: string = dirname(dirname(scriptPath))

/** The four namespace keys `SOURCE_VALIDATOR` fills, which is also the shape of one loaded validator surface. */
type SourceValidatorKey = "registry" | "sdk" | "manifest" | "rosterData"

// Step 1 targets: the live rules of a checkout. Kept as a table so the fatal diagnostic below
// can name every path it tried instead of one bare "Cannot find module".
const SOURCE_VALIDATOR: Record<SourceValidatorKey, string> = {
  registry: "../packages/mpd-ext-plugin/src/registry.ts",
  sdk: "../packages/mpd-ext-plugin/src/sdk.ts",
  manifest: "../packages/mpd-ext-plugin/src/manifest.ts",
  // The base-roster name table the runtime screens extension roles against: `registry.ts`
  // builds its private BASE_ROLE_NAME_KEYS from this same module, so the CLI screens with
  // the same table and the same `roleNameKey`, not with a re-implementation of either.
  rosterData: "../packages/mpd-roles-plugin/src/roles.data.ts",
}
// Step 2 target: the compiled entry a PACKED artifact carries, generated by
// `scripts/pack-mpd.ts` (its VALIDATOR_SHIM_EXPORTS is the twin of this list, and
// `scripts/verify-pack-closure.ts` fails when the two drift apart).
const COMPILED_VALIDATOR: string = "../packages/mpd-ext-plugin/dist/validator.js"
/** The exports the compiled entry must carry: `pack-mpd.ts` writes them, and a partial shim is refused. */
const REQUIRED_COMPILED_EXPORTS: readonly string[] = [
  "ROLES",
  "MPD_EXT_CONTRACT",
  "buildExtension",
  "roleNameKey",
  "roleNameCollisionReason",
  "discoverPlane",
  "projectExtensionsDir",
  "userExtensionsDir",
  "bundleExtensionsDir",
]

/** One module import that failed, with the diagnostic it produced. */
interface ValidatorAttempt {
  /** The path exactly as `SOURCE_VALIDATOR` / `COMPILED_VALIDATOR` spells it. */
  target: string
  /** One readable line: the errno/name tag plus the message, never a bare "[object Object]". */
  error: string
}

/** The registry surface this CLI consumes from `packages/mpd-ext-plugin/src/registry.ts`. */
interface RegistrySurface {
  /** Build one extension through the SAME validator apply-time discovery calls. */
  buildExtension(options: BuildExtensionOptions): BuildExtensionResult
  /** The collapsed name key the base roster and an extension role are compared by. */
  roleNameKey(name: string): string
  /** The roster's own collision sentence, so a refusal is reported in the roster's words. */
  roleNameCollisionReason(extensionId: string, name: string, item: string, takenBy: string): string
}

/** The contract surface this CLI consumes from `packages/mpd-ext-plugin/src/sdk.ts`. */
interface SdkSurface {
  /** The frozen descriptor contract: the manifest file name and the three published grammars. */
  MPD_EXT_CONTRACT: typeof MPD_EXT_CONTRACT
}

/** The discovery surface this CLI consumes from `packages/mpd-ext-plugin/src/manifest.ts`. */
interface ManifestSurface {
  /** Sweep one plane root for `<dir>/<extension>/mpd-ext.json`; never throws. */
  discoverPlane(options: DiscoverPlaneOptions): DiscoveryResult
  /** The per-session project plane root for one workspace. */
  projectExtensionsDir(workspaceRoot: string): string
  /** The host-wide user plane root (`~/.mpd/extensions`). */
  userExtensionsDir(): string
  /** The host-wide bundle plane root (`<bundle>/extensions`). */
  bundleExtensionsDir(): string
}

/** The base-roster surface this CLI screens extension roles against (`packages/mpd-roles-plugin/src/roles.data.ts`). */
interface RosterSurface {
  /** The base-roster table; only `name` is read, and only through the registry's own `roleNameKey`. */
  ROLES: MpdRoleSpec[]
}

/** Any one of the four validator surfaces; the `SOURCE_VALIDATOR` key decides which one a target supplies. */
type ValidatorSurface = RegistrySurface | SdkSurface | ManifestSurface | RosterSurface

/** The namespaces loaded so far, keyed exactly as `SOURCE_VALIDATOR` is; a failed target stays absent. */
interface LoadedValidatorNamespaces {
  /** `packages/mpd-ext-plugin/src/registry.ts`, once it imported. */
  registry?: RegistrySurface
  /** `packages/mpd-ext-plugin/src/sdk.ts`, once it imported. */
  sdk?: SdkSurface
  /** `packages/mpd-ext-plugin/src/manifest.ts`, once it imported. */
  manifest?: ManifestSurface
  /** `packages/mpd-roles-plugin/src/roles.data.ts`, once it imported. */
  rosterData?: RosterSurface
}

/**
 * The compiled entry (`packages/mpd-ext-plugin/dist/validator.js`): ONE module re-exporting all four
 * source surfaces, plus the open index view the required-export probe reads its names through.
 */
type CompiledValidatorNamespace = RegistrySurface & SdkSurface & ManifestSurface & RosterSurface & Record<string, unknown>

/** What {@link loadSharedValidator} resolved: which mode answered, and the four surfaces the CLI reads. */
interface SharedValidator {
  /** `source` when the checkout's TypeScript sources answered, `compiled` when the packed entry did. */
  mode: "source" | "compiled"
  /** Descriptor validation and the role-name rules. */
  registry: RegistrySurface
  /** The frozen descriptor contract. */
  sdk: SdkSurface
  /** The three plane roots and the discovery sweep. */
  manifest: ManifestSurface
  /** The base-roster table. */
  rosterData: RosterSurface
  /** Every target that failed, in table order; empty in source mode. */
  attempts: ValidatorAttempt[]
  /** The compiled entry that answered, present only in compiled mode. */
  target?: string
}

/** One readable line for a failed import: the errno/name tag plus the message, never a bare "[object Object]". */
function describeModuleError(error: unknown): string {
  if (error === null || typeof error !== "object") return String(error)
  // A thrown Node error is an object whose `code`/`name`/`message` are the only fields this line reads, and
  // the `typeof` above cannot narrow `object` to that shape; the assertion is exactly that shape check.
  const failure = error as { code?: string; name?: string; message?: unknown }
  /** The errno (`ERR_MODULE_NOT_FOUND`) or the error class name, when the value carries one. */
  const tag = failure.code ?? failure.name
  return (tag === undefined ? "" : tag + ": ") + String(failure.message ?? failure)
}

/**
 * Load the ONE validator this CLI shares with the runtime, sources first, compiled entry
 * second. Never throws: a run with no validator prints every path it tried and exits 1 —
 * a validator-less CLI must never "validate" anything with a fallback rule set.
 */
async function loadSharedValidator(): Promise<SharedValidator> {
  /** One entry per target that failed, in table order, so the fatal report names every path tried. */
  const attempts: ValidatorAttempt[] = []
  /** The namespaces loaded so far, keyed exactly as `SOURCE_VALIDATOR` is. */
  const loaded: LoadedValidatorNamespaces = {}
  /** Cleared by the first failing import: a partial surface must never be reported as source mode. */
  let complete = true
  // `Object.entries` widens every key to `string`; the table's own keys are the four surfaces above, which
  // is what the keyed write relies on.
  for (const [key, rel] of Object.entries(SOURCE_VALIDATOR) as Array<[SourceValidatorKey, string]>) {
    try {
      loaded[key] = await import(new URL(rel, import.meta.url).href)
    } catch (error) {
      complete = false
      attempts.push({ target: rel, error: describeModuleError(error) })
    }
  }
  if (complete) {
    // `complete` survives only when all four targets imported, so every key below is present; a dynamic
    // import cannot carry the module's own types, which is why each one is asserted right here.
    return { mode: "source", registry: loaded.registry!, sdk: loaded.sdk!, manifest: loaded.manifest!, rosterData: loaded.rosterData!, attempts }
  }
  try {
    // `dist/validator.js` carries all four surfaces in one namespace, and the export probe below is what
    // makes this assertion checked rather than assumed.
    const compiled: CompiledValidatorNamespace = await import(new URL(COMPILED_VALIDATOR, import.meta.url).href)
    /** Required exports this compiled entry does NOT carry; an empty list is the only acceptable one. */
    const missing = REQUIRED_COMPILED_EXPORTS.filter((name: string) => compiled[name] === undefined)
    if (missing.length === 0) {
      // In compiled mode all four namespaces ARE this one module: the bundle carries the
      // registry, the contract, the manifest helpers and the roster table.
      return { mode: "compiled", registry: compiled, sdk: compiled, manifest: compiled, rosterData: compiled, attempts, target: COMPILED_VALIDATOR }
    }
    attempts.push({ target: COMPILED_VALIDATOR, error: "loaded, but missing exports: " + missing.join(", ") })
  } catch (error) {
    attempts.push({ target: COMPILED_VALIDATOR, error: describeModuleError(error) })
  }
  process.stderr.write("mpd-ext: cannot load the shared validator — this CLI deliberately has no rule set of its own, so it refuses to run without one.\n")
  for (const attempt of attempts) process.stderr.write("  tried " + attempt.target + ": " + attempt.error + "\n")
  process.stderr.write("  from a checkout: run it under bun (`bun scripts/mpd-ext.ts …`) so the TypeScript sources load\n")
  process.stderr.write("  from a packed artifact: re-run `npm run pack` — the packer emits packages/mpd-ext-plugin/dist/validator.js for exactly this case\n")
  process.exit(1)
}

/** The ONE validator this run resolved; no command below runs without it. */
const validator: SharedValidator = await loadSharedValidator()
/** Descriptor validation: the rule set the runtime and this CLI share. */
const registry: RegistrySurface = validator.registry
/** The frozen descriptor contract, read for the file name and the three grammars. */
const sdk: SdkSurface = validator.sdk
/** The three plane roots and the discovery sweep. */
const manifest: ManifestSurface = validator.manifest
/** The base-roster table, read only through the registry's own key function. */
const rosterData: RosterSurface = validator.rosterData
/** Every base-roster name key, so a derived role name the roster owns is caught before anything is written. */
const BASE_ROLE_NAME_KEYS: Set<string> = new Set(rosterData.ROLES.map((role: MpdRoleSpec) => registry.roleNameKey(role.name)))

/** The manifest file name, read FROM the contract so a rename there cannot leave this CLI behind. */
const MANIFEST_FILE: string = sdk.MPD_EXT_CONTRACT.manifestFile
/** The three discovery planes, in precedence order, as `--plane` names them. */
const PLANES: readonly MpdExtensionPlane[] = ["project", "user", "bundle"]

/** One line on stdout — this CLI's only success channel. */
function line(text: string): void {
  process.stdout.write(text + "\n")
}

/** Report one problem on stderr and mark the run failed; the exit code is never raised directly. */
function fail(text: string): void {
  process.stderr.write(text + "\n")
  process.exitCode = 1
}

/** A non-fatal problem: reported on stderr, and it never changes the exit code. */
function warn(text: string): void {
  process.stderr.write(text + "\n")
}

/** An extension located on disk: the root every asset path resolves against, and its manifest. */
interface LocatedExtension {
  /** The extension directory: the given directory, or the manifest's own directory when a file was named. */
  root: string
  /** Absolute path of the `mpd-ext.json` this run validates. */
  manifestPath: string
}

/** Resolve `<dir>` (an extension directory) or a direct manifest path to {root, manifestPath}. */
function locateExtension(input: string | undefined): LocatedExtension | undefined {
  /** The caller's path resolved against the process cwd; "" when the argument was omitted entirely. */
  const target = resolve(input ?? "")
  if (!existsSync(target)) return undefined
  if (statSync(target).isFile()) {
    if (target.endsWith(MANIFEST_FILE)) return { root: dirname(target), manifestPath: target }
    return undefined
  }
  /** The manifest a directory must carry to be an extension root. */
  const manifestPath = join(target, MANIFEST_FILE)
  if (!existsSync(manifestPath)) return undefined
  return { root: target, manifestPath }
}

/** What one extension's validation came back as: per-item errors plus whichever record it produced. */
interface LoadedExtension {
  /** Every problem reported, one line per item; empty means the extension loads. */
  errors: MpdExtLoadError[]
  /** The loaded entry, or `undefined` when the descriptor was refused. */
  entry: ExtensionEntry | undefined
  /** The wholesale refusal record, or `undefined` when an entry was produced. */
  rejected: RejectedExtension | undefined
}

/** Load one extension through the RUNTIME validator. Never throws. */
function loadExtension(input: string | undefined, plane: MpdExtensionPlane = "user"): LoadedExtension {
  /** The extension on disk, when the input names one. */
  const located = locateExtension(input)
  if (located === undefined) {
    return { errors: [{ item: input ?? "", reason: `no ${MANIFEST_FILE} found at or under "${resolve(input ?? "")}"` }], entry: undefined, rejected: undefined }
  }
  /** The manifest bytes as read; a read failure is one item error, never a throw. */
  let raw: string
  try {
    raw = readFileSync(located.manifestPath, "utf8")
  } catch (error) {
    return { errors: [{ item: located.manifestPath, reason: `cannot read: ${String(error)}` }], entry: undefined, rejected: undefined }
  }
  /** The parsed manifest, kept `unknown`: the validator re-checks every field, nothing is trusted here. */
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch (error) {
    return {
      errors: [{ item: located.manifestPath, reason: `invalid JSON: ${String(error)}` }],
      entry: undefined,
      rejected: { id: located.root, plane, origin: "directory", root: located.root, source: located.manifestPath, errors: [{ item: MANIFEST_FILE, reason: `invalid JSON: ${String(error)}` }] },
    }
  }
  // The parsed document is on-disk data, so its `id` is read through the shape the one use below needs.
  /** The manifest's own `id`, when it is a non-empty string; the validator enforces the grammar itself. */
  const declaredId = (parsed as { id?: unknown } | null)?.id
  /** The id this run labels the extension with (`unnamed` until the validator decides otherwise). */
  const id = typeof declaredId === "string" && declaredId.length > 0 ? declaredId : "unnamed"
  try {
    /** The validator's verdict: a loadable entry XOR a rejected record, never both. */
    const built = registry.buildExtension({
      input: parsed,
      plane,
      origin: "directory",
      root: located.root,
      source: located.manifestPath,
      fallbackId: id,
      providerName: `mpd-ext:${id}`,
    })
    if (built.rejected !== undefined) return { errors: built.rejected.errors, entry: undefined, rejected: built.rejected }
    // "entry XOR rejected" is the validator's contract and `rejected` was just ruled out; should that contract
    // ever break, the read below throws exactly where the original's did — into this same catch.
    return { errors: built.entry!.errors, entry: built.entry!, rejected: undefined }
  } catch (error) {
    return { errors: [{ item: MANIFEST_FILE, reason: `validation crashed: ${String(error)}` }], entry: undefined, rejected: undefined }
  }
}

/** Render one loaded extension's live counts: the summary line every command prints. */
function describeEntry(entry: ExtensionEntry): string {
  /** The live per-kind counts, as the validator recorded them on the entry. */
  const counts = entry.contributions
  return `${counts.skills} skill(s), ${counts.flows} flow(s), ${counts.roles} role(s), ${counts.mcp} mcp server(s)`
}

/** `validate <dir>` — the CI gate. */
function runValidate(input: string | undefined, plane: MpdExtensionPlane): void {
  if (input === undefined) {
    fail("mpd-ext validate: an extension directory is required")
    return
  }
  /** The validator's verdict on this input. */
  const result = loadExtension(input, plane)
  /** The id every line below is labelled with: the entry's, the refusal's, or the resolved input path. */
  const id = result.entry?.id ?? result.rejected?.id ?? resolve(input)
  line(`[mpd-ext] validate ${resolve(input)} (plane=${plane})`)
  line(`  extension "${id}": ${result.entry === undefined ? "REJECTED" : "loadable"}`)
  if (result.entry !== undefined) line(`  contributes: ${describeEntry(result.entry)}`)
  for (const error of result.errors) line(`  error ${error.item}: ${error.reason}`)
  for (const pending of result.entry?.pending ?? []) line(`  pending ${pending.item}: ${pending.reason}`)
  if (result.errors.length > 0) {
    fail(`[mpd-ext] ${result.errors.length} problem(s) — this extension would not load`)
    return
  }
  line("[mpd-ext] ok")
}

/** `list` — what this host would discover. */
function runList(): void {
  /** The three planes in precedence order, each with the root this host resolves it to. */
  const roots: ReadonlyArray<readonly [MpdExtensionPlane, string]> = [
    ["project", manifest.projectExtensionsDir(process.cwd())],
    ["user", manifest.userExtensionsDir()],
    ["bundle", manifest.bundleExtensionsDir()],
  ]
  /** Ids already claimed, each mapped to the plane that claimed it: the first claimant wins. */
  const seen = new Map<string, string>()
  /** How many per-item problems were recorded; the host still boots with any number of them. */
  let problems = 0
  for (const [plane, dir] of roots) {
    line(`[mpd-ext] ${plane} plane: ${dir}`)
    /** One plane's sweep: what loaded, and what was refused wholesale. */
    const discovered = manifest.discoverPlane({ plane, dir, providerNameFor: (id: string) => `mpd-ext:${id}`, warn: (text: string): void => { problems += 1; line(`  warn: ${text}`) } })
    for (const entry of discovered.entries) {
      if (seen.has(entry.id)) {
        line(`  ${entry.id}: shadowed by the ${seen.get(entry.id)} plane (first wins)`)
        continue
      }
      seen.set(entry.id, plane)
      line(`  ${entry.id}: ${entry.enabled ? "enabled" : "disabled"} — ${describeEntry(entry)}${entry.errors.length > 0 ? ` — ${entry.errors.length} error(s)` : ""}`)
      for (const error of entry.errors) line(`    error ${error.item}: ${error.reason}`)
    }
    for (const rejected of discovered.rejected) {
      problems += 1
      line(`  ${rejected.id}: REJECTED — ${rejected.errors.map((error: MpdExtLoadError) => `${error.item}: ${error.reason}`).join("; ")}`)
    }
    if (discovered.entries.length === 0 && discovered.rejected.length === 0) line("  (none)")
  }
  if (problems > 0) {
    line(`[mpd-ext] ${problems} problem(s) recorded (the loader still boots: every failure is contained per item)`)
  }
}
/**
 * The generic template — the ONLY source of truth for what `scaffold` emits.
 *
 * The placeholder to rewrite is the template manifest's OWN `id`, so this CLI
 * knows no derived-name pattern at all: it renames paths and rewrites text.
 */
const TEMPLATE_DIR: string = join(repoRoot, "templates", "mpd-extension")
/** Extensions whose copied bodies get the token rewrite; every other file is copied byte-for-byte. */
const TEXT_EXTENSIONS: readonly string[] = [".json", ".md", ".ts"]

/** The template manifest as this CLI reads it: the placeholder id and the role names to screen. */
interface TemplateManifest {
  /** The placeholder token every copied path segment and text body carries; the copy renames it. */
  id: string
  /** The declared contributions; only `roles[].name` is read, and only to screen it against the base roster. */
  contributes?: {
    /** Declared roles; `name` stays `unknown` because the document is data and is stringified at the screen. */
    roles?: ReadonlyArray<{ name?: unknown }>
  }
}

/**
 * The contract's own `serverName` bound, parsed OUT of the contract pattern — never the
 * literal 32 — so widening the contract widens this CLI with it.
 */
function serverNameMaxLength(): number | undefined {
  /** The `{1,<n>}` bound of the contract's server-name pattern; `null` when the pattern carries none. */
  const match = /\{1,(\d+)\}/.exec(sdk.MPD_EXT_CONTRACT.serverNamePattern)
  if (match === null) {
    fail(`mpd-ext: cannot read a maximum length out of the contract's serverName pattern ${sdk.MPD_EXT_CONTRACT.serverNamePattern}`)
    return undefined
  }
  return Number(match[1])
}

/** The derived `serverName`: the extension name, capped by the contract's own bound. */
function serverNameFor(name: string): string {
  return name.slice(0, serverNameMaxLength() ?? name.length)
}

/** The placeholder token, read FROM the template (never hard-coded here). */
function templateToken(): string {
  return readJson<TemplateManifest>(join(TEMPLATE_DIR, MANIFEST_FILE)).id
}

/** The three token-rewritten name sets `scaffold` screens before it writes anything. */
interface TemplateDerivedNames {
  /** Immediate skill directories, token-rewritten; empty when the template ships no skills root. */
  skillDirs: string[]
  /** Flow ids (`<name>.json` without its extension), token-rewritten; empty without a flows root. */
  flowIds: string[]
  /** Declared role names, token-rewritten, in manifest order. */
  roleNames: string[]
}

/** The derived names the copy will carry, read from the template's OWN paths and manifest. */
function templateDerivedNames(token: string, name: string): TemplateDerivedNames {
  /** Rewrite every occurrence of the template token in one path segment or text value. */
  const rename = (value: string): string => value.split(token).join(name)
  /** The template's skills root; its absence means the template declares no skill asset at all. */
  const skillsRoot = join(TEMPLATE_DIR, "skills")
  /** The template's flows root; its absence means the template declares no flow asset at all. */
  const flowsRoot = join(TEMPLATE_DIR, "flows")
  /** Token-rewritten skill directory names, walked only when the root exists. */
  const skillDirs = existsSync(skillsRoot)
    ? readdirSync(skillsRoot, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => rename(entry.name))
    : []
  /** Token-rewritten flow ids, taken from the `.json` documents only. */
  const flowIds = existsSync(flowsRoot)
    ? readdirSync(flowsRoot)
        .filter((entry) => entry.endsWith(".json"))
        .map((entry) => rename(entry.slice(0, -".json".length)))
    : []
  /** The template's own manifest, read for the role names it declares. */
  const templateManifest = readJson<TemplateManifest>(join(TEMPLATE_DIR, MANIFEST_FILE))
  /** Token-rewritten role names; `String()` keeps one malformed item from crashing the whole derivation. */
  const roleNames = (templateManifest.contributes?.roles ?? []).map((item: { name?: unknown }) => rename(String(item.name)))
  return { skillDirs, flowIds, roleNames }
}

/**
 * The base roster screens an extension role by its collapsed name key and always wins
 * (`packages/mpd-ext-plugin/src/registry.ts:746-748`). Screen it HERE, before a single
 * byte is written, and report it with the roster's own sentence
 * (`roleNameCollisionReason`, `registry.ts:236-238`) instead of as a CLI defect.
 */
function baseRosterRoleConflicts(name: string, roleNames: string[]): string[] {
  /** One refusal sentence per role name the base roster already owns, in manifest order. */
  const conflicts: string[] = []
  roleNames.forEach((roleName: string, index: number) => {
    if (BASE_ROLE_NAME_KEYS.has(registry.roleNameKey(roleName))) {
      conflicts.push(registry.roleNameCollisionReason(name, roleName, `contributes.roles[${index}]`, "the base roster"))
    }
  })
  return conflicts
}

/** Copy the template tree, renaming every path segment and rewriting every text body. */
function copyTemplateTree(sourceRoot: string, targetRoot: string, token: string, name: string): string[] {
  /** Every copied path, relative to the target root, in walk order. */
  const copied: string[] = []
  /** Copy one directory level: rename each segment, rewrite each text body, then descend. */
  const walk = (relative: string): void => {
    /** The directory this level reads: the source root itself at the top, else the joined relative path. */
    const sourceDir = relative === "" ? sourceRoot : join(sourceRoot, relative)
    for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
      /** This entry's path relative to the SOURCE root, before the token rewrite. */
      const child = relative === "" ? entry.name : join(relative, entry.name)
      /** The same path with every segment's token rewritten — the path the copy will carry. */
      const renamed = child
        .split(sep)
        .map((segment: string) => segment.split(token).join(name))
        .join(sep)
      /** Absolute destination path of this entry inside the copy. */
      const destination = join(targetRoot, renamed)
      if (entry.isDirectory()) {
        mkdirSync(destination, { recursive: true })
        walk(child)
        continue
      }
      /** The source bytes; text files get the token rewrite, every other file is copied verbatim. */
      const body = readFileSync(join(sourceRoot, child), "utf8")
      writeFileSync(destination, TEXT_EXTENSIONS.includes(extname(entry.name)) ? body.split(token).join(name) : body)
      copied.push(renamed)
    }
  }
  walk("")
  return copied
}

/** One JSON object as an on-disk manifest holds it: keys are open and no value is trusted. */
type JsonObject = Record<string, unknown>

/**
 * The manifest document `finishManifest` edits in place: the one key it drops or rewrites. Every other
 * key survives the JSON round-trip untouched, so only what is read or written is named here.
 */
interface ScaffoldManifest {
  /** The declared contributions; `mcp` is the one kind `--with-mcp` keeps, drops or rewrites. */
  contributes?: {
    /** The declared stdio servers; `unknown` until `Array.isArray` proves the document carries a list. */
    mcp?: unknown
  }
}

/**
 * The two documented manifest edits on top of the copy: the contract caps
 * `serverName` at 32 characters, and WITHOUT `--with-mcp` the `mcp` contribution
 * (and its server file) is dropped, so the default copy contributes three kinds.
 */
function finishManifest(target: string, name: string, withMcp: boolean): void {
  /** The copied manifest this function rewrites in place. */
  const manifestPath = join(target, MANIFEST_FILE)
  /** The copied document, asserted to the two keys this rewrite touches (`readJson` is that boundary). */
  const parsed = readJson<ScaffoldManifest>(manifestPath)
  /** The declared contributions, created empty when the copy declares none. */
  const contributes = parsed.contributes ?? {}
  if (!withMcp) delete contributes.mcp
  if (Array.isArray(contributes.mcp)) {
    // `Array.isArray` narrows to `any[]`; the callback names the shape a manifest item has, and the spread
    // preserves every key the author wrote besides the replaced `serverName`.
    contributes.mcp = contributes.mcp.map((item: JsonObject) => ({ ...item, serverName: serverNameFor(name) }))
  }
  parsed.contributes = contributes
  writeFileSync(manifestPath, JSON.stringify(parsed, null, 2) + "\n")
  if (!withMcp) rmSync(join(target, "server.ts"), { force: true })
}

/**
 * The per-file comparison A3 requires: a copy is the template modulo the token
 * rewrite and the documented `--with-mcp` drop — proven file by file, never
 * asserted in prose. Returns one line per difference (empty means equivalent).
 */
function compareCopyToTemplate(templateRoot: string, copyRoot: string, token: string, name: string, withMcp: boolean): string[] {
  /** One line per difference found; empty means the copy is the template modulo the documented edits. */
  const problems: string[] = []
  /** Rewrite every occurrence of the template token in one path segment. */
  const rename = (value: string): string => value.split(token).join(name)
  /** Every path the template carries, token-rewritten: the content the copy is expected to have. */
  const expected = new Set<string>()
  /** Compare one template directory level against the copy. */
  const walk = (relative: string): void => {
    /** The template directory this level reads. */
    const sourceDir = relative === "" ? templateRoot : join(templateRoot, relative)
    for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
      /** This entry's path relative to the TEMPLATE root, before the token rewrite. */
      const child = relative === "" ? entry.name : join(relative, entry.name)
      if (entry.isDirectory()) {
        walk(child)
        continue
      }
      /** The path the copy must carry for this template file. */
      const target = child.split(sep).map(rename).join(sep)
      expected.add(target)
      /** The template's own bytes, the base of the expected copy content. */
      const source = readFileSync(join(templateRoot, child), "utf8")
      if (!withMcp && child === "server.ts") {
        if (existsSync(join(copyRoot, target))) problems.push(`${target}: the default copy must drop the mcp server`)
        continue
      }
      if (!existsSync(join(copyRoot, target))) {
        problems.push(`${target}: missing from the copy`)
        continue
      }
      /** The bytes the copy must hold: the token-rewritten body for text files, the raw body otherwise. */
      const wantText = TEXT_EXTENSIONS.includes(extname(child)) ? source.split(token).join(name) : source
      /** The bytes the copy actually holds. */
      const gotText = readFileSync(join(copyRoot, target), "utf8")
      if (child === MANIFEST_FILE) {
        // The manifest is compared as a DOCUMENT, not as text, because `finishManifest` rewrote its JSON.
        /** The expected manifest document, asserted to the shape the replay below produces. */
        const wantObject = JSON.parse(wantText) as ScaffoldManifest
        /** Its declared contributions, replayed exactly as `finishManifest` rewrote the copy's. */
        const wantContributes = wantObject.contributes ?? {}
        if (!withMcp) delete wantContributes.mcp
        if (Array.isArray(wantContributes.mcp)) {
          wantContributes.mcp = wantContributes.mcp.map((item: JsonObject) => ({ ...item, serverName: serverNameFor(name) }))
        }
        wantObject.contributes = wantContributes
        if (gotText !== JSON.stringify(wantObject, null, 2) + "\n") {
          problems.push(`${target}: manifest bytes differ from the canonical token-rewritten template (mcp ${withMcp ? "kept" : "dropped"})`)
        }
        continue
      }
      if (gotText !== wantText) problems.push(`${target}: bytes differ from the template modulo the token rewrite`)
    }
  }
  walk("")
  /** Paths the copy carries that the template does not — one extra file is a difference too. */
  const extra: string[] = []
  /** Walk the COPY for paths the template never had. */
  const walkCopy = (relative: string): void => {
    /** The copy directory this level reads. */
    const dir = relative === "" ? copyRoot : join(copyRoot, relative)
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      /** This entry's path relative to the COPY root. */
      const child = relative === "" ? entry.name : join(relative, entry.name)
      if (entry.isDirectory()) walkCopy(child)
      else if (!expected.has(child)) extra.push(child)
    }
  }
  walkCopy("")
  for (const path of extra) problems.push(`${path}: not part of the template`)
  return problems
}

/** What `scaffold` takes from the command line: where the copy goes, and whether the MCP kind is kept. */
interface ScaffoldOptions {
  /** `--dir <path>`: the directory the copy is created in; absent means the process cwd. */
  dir?: string
  /** `--with-mcp`: keep the template's stdio MCP contribution and its server file. */
  withMcp: boolean
}

/**
 * `scaffold <name> --dir <path> [--with-mcp]` — COPY `templates/mpd-extension/`
 * and rewrite its placeholder (the template manifest's own id). The template is
 * the single source of truth: this CLI emits no code of its own.
 */
function runScaffold(name: string | undefined, options: ScaffoldOptions): void {
  if (typeof name !== "string" || name.length === 0) {
    fail("mpd-ext scaffold: an extension name is required")
    return
  }
  if (!new RegExp(sdk.MPD_EXT_CONTRACT.idPattern).test(name)) {
    fail(`mpd-ext scaffold: "${name}" must match ${sdk.MPD_EXT_CONTRACT.idPattern}`)
    return
  }
  if (!existsSync(join(TEMPLATE_DIR, MANIFEST_FILE))) {
    fail(`mpd-ext scaffold: the template "${TEMPLATE_DIR}" is missing — it is the only source of this command's output`)
    return
  }
  /** The template's placeholder token, read from the template's own manifest. */
  const token = templateToken()
  if (typeof token !== "string" || token.length === 0) {
    fail("mpd-ext scaffold: the template manifest carries no placeholder id, so a copy cannot be named")
    return
  }
  /** The names the copy will carry, screened below BEFORE anything is written. */
  const derived = templateDerivedNames(token, name)
  /** The two derived-name sets the skill-name grammar screens, with the label each refusal prints. */
  const screens: ReadonlyArray<readonly [string, string[]]> = [["skill name", derived.skillDirs], ["flow id", derived.flowIds]]
  for (const [label, values] of screens) {
    for (const value of values) {
      if (!new RegExp(sdk.MPD_EXT_CONTRACT.skillNamePattern).test(value)) {
        fail(`mpd-ext scaffold: the derived ${label} "${value}" violates the skill-name grammar ${sdk.MPD_EXT_CONTRACT.skillNamePattern} — pick a name without a trailing dash`)
        return
      }
    }
  }
  /** The directory the copy is created in; an absent `--dir` means the process cwd. */
  const parent = resolve(options.dir ?? ".")
  /** The directory the finished copy will occupy. */
  const target = join(parent, name)
  if (existsSync(target)) {
    fail(`mpd-ext scaffold: "${target}" already exists — scaffolding never overwrites`)
    return
  }
  /** One refusal sentence per derived role name the base roster already owns. */
  const roleConflicts = baseRosterRoleConflicts(name, derived.roleNames)
  if (roleConflicts.length > 0) {
    fail(`mpd-ext scaffold: refused — "${name}" would declare a role name the base roster already owns`)
    warn(`  nothing was written to ${target}`)
    for (const reason of roleConflicts) line(`  refused: ${reason}`)
    return
  }
  /** Whether the copy keeps the template's stdio MCP contribution and its server file. */
  const withMcp = options.withMcp === true
  /** The contract's serverName bound, or the name's own length when the pattern carries no bound. */
  const maxServerName = serverNameMaxLength() ?? name.length
  if (name.length > maxServerName) {
    warn(`mpd-ext scaffold: warning: ${sdk.MPD_EXT_CONTRACT.serverNamePattern} caps serverName at ${maxServerName} characters, so the copy declares "${serverNameFor(name)}" instead of "${name}"`)
  }

  // Build in a STAGING container beside the target and move it into place only after the
  // runtime validator accepts it: a refusal (a CONTRACT refusal, never a CLI defect) can
  // then never leave a half-written, unloadable extension behind. The container level is
  // deliberate — discovery inspects only a root's IMMEDIATE children for `mpd-ext.json`,
  // so an extension staged one level down is never discoverable while it is being built.
  /** The staging container beside the target: its children are invisible to discovery. */
  const stagingContainer = join(parent, `.mpd-ext-scaffold-${process.pid}-${Date.now()}`)
  /** The staged copy, renamed onto `target` only after the validator accepts it. */
  const stagingTarget = join(stagingContainer, name)
  try {
    mkdirSync(stagingTarget, { recursive: true })
    /** Every file copied from the template, in walk order. */
    const copied = copyTemplateTree(TEMPLATE_DIR, stagingTarget, token, name)
    finishManifest(stagingTarget, name, withMcp)

    /** The validator's verdict on the staged copy — the gate between staging and the target. */
    const result = loadExtension(stagingTarget, "user")
    if (result.errors.length > 0 || result.entry === undefined) {
      fail(`mpd-ext scaffold: refused — the copy would not load as "${name}"; nothing was written to ${target}`)
      for (const error of result.errors) line(`  error ${error.item}: ${error.reason}`)
      return
    }
    renameSync(stagingTarget, target)
    line(`[mpd-ext] scaffolded "${name}" at ${target}`)
    line(`  copied ${copied.length} file(s) from templates/mpd-extension${withMcp ? "" : " (the mcp contribution and server.ts were dropped)"}`)
    line(`  contributes: ${describeEntry(result.entry)}`)
    line(`  next: bun scripts/mpd-ext.ts validate ${target}`)
  } finally {
    // a no-op after a successful rename; the only tree it removes is a refused staging one
    rmSync(stagingContainer, { recursive: true, force: true })
  }
}
// ── self-test ───────────────────────────────────────────────────────────────

/** One child CLI run: its exit status and both captured streams. */
interface ChildRun {
  /** Exit status, or `null` when the child was killed by a signal instead of exiting. */
  status: number | null
  /** Everything the child wrote to stdout. */
  stdout: string
  /** Everything the child wrote to stderr. */
  stderr: string
}

/** Run this CLI again as a child process and capture its streams; the self-test's only subject. */
function runChild(args: string[]): ChildRun {
  /** The child's outcome; `utf8` makes both streams strings rather than buffers. */
  const result = spawnSync(process.execPath, [scriptPath, ...args], { encoding: "utf8" })
  return { status: result.status, stdout: result.stdout ?? "", stderr: result.stderr ?? "" }
}

/** A copied manifest as the self-test reads it: the contribution kinds the scaffold arms assert on. */
interface CopiedManifest {
  /** The declared contributions; every copy carries this key (`finishManifest` always writes it). */
  contributes: {
    /** Declared stdio servers, present on a `--with-mcp` copy and absent on a default one. */
    mcp?: ReadonlyArray<{ serverName: string }>
  }
}

/** A `--with-mcp` copy's manifest: the server list the serverName-cap assertion reads is always there. */
interface McpCopiedManifest {
  /** The declared contributions, with the server list a `--with-mcp` copy always carries. */
  contributes: {
    /** Declared stdio servers, in manifest order. */
    mcp: ReadonlyArray<{ serverName: string }>
  }
}

/** The CLI's own checks: both scaffold arms, the refusals, a negative control and the usage guard. */
function selfTest(): void {
  /** The temp directory every arm writes into; removed in the `finally` below. */
  const sandbox = mkdtempSync(join(tmpdir(), "mpd-ext-cli-selftest-"))
  /** How many checks ran, so the pass line reports the size of the proof. */
  let checks = 0
  /** Record one check: `ok` on stdout, `FAIL` (which sets the exit code) on stderr. */
  const expect = (condition: boolean, label: string): void => {
    checks += 1
    if (condition) line(`  ok ${label}`)
    else fail(`  FAIL ${label}`)
  }
  try {
    // 0. the shared validator surface. Both modes must expose the same four namespaces: in a
    //    checkout they are the sources, in a packed artifact they are the packer-generated
    //    compiled entry. A partially-populated shim passes an import and still breaks the
    //    commands, so assert the surfaces the CLI actually calls.
    expect(
      typeof registry.buildExtension === "function" &&
        typeof registry.roleNameKey === "function" &&
        typeof registry.roleNameCollisionReason === "function" &&
        typeof sdk.MPD_EXT_CONTRACT?.manifestFile === "string" &&
        typeof manifest.discoverPlane === "function" &&
        typeof manifest.projectExtensionsDir === "function" &&
        typeof manifest.userExtensionsDir === "function" &&
        typeof manifest.bundleExtensionsDir === "function" &&
        Array.isArray(rosterData.ROLES),
      `the shared validator exposes the four surfaces the CLI uses (${validator.mode} mode)`,
    )

    // 1. the template is the source of truth, so it must load with all four kinds.
    /** The template validated as-is: it must be loadable with all four contribution kinds. */
    const template = runChild(["validate", TEMPLATE_DIR])
    expect(template.status === 0, `validate accepts templates/mpd-extension (got ${template.status}): ${template.stderr.trim()}`)
    expect(template.stdout.includes("1 skill(s), 1 flow(s), 1 role(s), 1 mcp server(s)"), "the template declares all four contribution kinds")

    // 2. --with-mcp: the copy keeps all four kinds and IS the template, file by file.
    /** The `--with-mcp` scaffold run; its copy is compared against the template below. */
    const scaffold = runChild(["scaffold", "demo-ext", "--dir", sandbox, "--with-mcp"])
    expect(scaffold.status === 0, `scaffold --with-mcp exits 0 (got ${scaffold.status}): ${scaffold.stderr.trim()}`)
    /** The copy the `--with-mcp` run created. */
    const scaffolded = join(sandbox, "demo-ext")
    expect(existsSync(join(scaffolded, MANIFEST_FILE)), "scaffold wrote mpd-ext.json")
    for (const asset of ["skills/demo-ext-skill/SKILL.md", "flows/demo-ext-flow.json", "personas/demo-ext-reviewer.md", "server.ts"]) {
      expect(existsSync(join(scaffolded, asset)), `scaffold wrote ${asset}`)
    }
    /** The scaffold copy validated by a SECOND process, exactly as CI would call it. */
    const validated = runChild(["validate", scaffolded])
    expect(validated.status === 0, `validate accepts the scaffold (got ${validated.status}): ${validated.stderr.trim()}`)
    /** Per-file differences between the template and the `--with-mcp` copy; empty means equivalent. */
    const withMcpProblems = compareCopyToTemplate(TEMPLATE_DIR, scaffolded, templateToken(), "demo-ext", true)
    expect(withMcpProblems.length === 0, `the --with-mcp copy is the template modulo the token rewrite, file by file${withMcpProblems.length > 0 ? `: ${withMcpProblems.join("; ")}` : ""}`)

    // 3. the default arm: the copy DROPS the mcp contribution and its server file, and still loads.
    /** The default scaffold run: no `--with-mcp`, so the mcp kind must be dropped. */
    const plain = runChild(["scaffold", "demo-ext-plain", "--dir", sandbox])
    expect(plain.status === 0, `scaffold (no flag) exits 0 (got ${plain.status}): ${plain.stderr.trim()}`)
    /** The default copy's root, where the dropped server file must NOT appear. */
    const plainRoot = join(sandbox, "demo-ext-plain")
    expect(!existsSync(join(plainRoot, "server.ts")), "the default copy drops server.ts")
    expect(readJson<CopiedManifest>(join(plainRoot, MANIFEST_FILE)).contributes.mcp === undefined, "the default copy drops the manifest mcp entry")
    for (const asset of ["skills/demo-ext-plain-skill/SKILL.md", "flows/demo-ext-plain-flow.json", "personas/demo-ext-plain-reviewer.md"]) {
      expect(existsSync(join(plainRoot, asset)), `the default copy wrote ${asset}`)
    }
    /** The default copy validated by a second process; it must load with three kinds. */
    const plainValidated = runChild(["validate", plainRoot])
    expect(plainValidated.status === 0, `validate accepts the default copy (got ${plainValidated.status}): ${plainValidated.stderr.trim()}`)
    expect(plainValidated.stdout.includes("1 skill(s), 1 flow(s), 1 role(s), 0 mcp server(s)"), "the default copy contributes three kinds")
    /** Per-file differences between the template and the default copy; empty means equivalent. */
    const plainProblems = compareCopyToTemplate(TEMPLATE_DIR, plainRoot, templateToken(), "demo-ext-plain", false)
    expect(plainProblems.length === 0, `the default copy is the template modulo the token rewrite and the mcp drop, file by file${plainProblems.length > 0 ? `: ${plainProblems.join("; ")}` : ""}`)

    // 3b. an id longer than the contract's serverName bound: the cap comes from the contract
    //     pattern, it is WARNED rather than silent, and the copy still validates.
    /** An id deliberately longer than the contract's serverName bound, to force the cap. */
    const longId = "demo-ext-with-a-very-long-identifier-1234"
    // The contract bound the CLI read above; the `!` is the self-test's own precondition — a missing bound
    // already reddened the run through `fail`, and the comparison degrades to `false` exactly as before.
    /** The bound the contract pattern carries, read back out of that pattern. */
    const bound: number = serverNameMaxLength()!
    /** The long-id scaffold run; its copy must still validate. */
    const longRun = runChild(["scaffold", longId, "--dir", sandbox, "--with-mcp"])
    expect(longRun.status === 0, `scaffold accepts an id longer than the serverName bound (got ${longRun.status}): ${longRun.stderr.trim()}`)
    /** The long-id copy's manifest, read for the capped `serverName`. */
    const longManifest = readJson<McpCopiedManifest>(join(sandbox, longId, MANIFEST_FILE))
    expect(longId.length > bound, `the long-id fixture (${longId.length} chars) really is longer than the contract bound (${bound})`)
    expect(longManifest.contributes.mcp[0].serverName === longId.slice(0, bound), `the copied serverName is capped at the contract bound (${bound}), not at a literal`)
    expect(longRun.stderr.includes("caps serverName at"), "the cap is WARNED on stderr, never silent")
    expect(runChild(["validate", join(sandbox, longId)]).status === 0, "the long-id copy still validates")

    // 4. the refusals: a bad id, an existing target, and a DERIVED ROLE NAME the base roster owns.
    /** A scaffold run whose id violates the id grammar; it must be refused. */
    const badName = runChild(["scaffold", "Bad Name", "--dir", sandbox])
    expect(badName.status === 1, "scaffold refuses an id that violates the id grammar")
    expect(badName.stderr.includes("must match"), "the refusal names the id grammar")
    /** The same id scaffolded twice: the second run must refuse the existing target. */
    const existing = runChild(["scaffold", "demo-ext", "--dir", sandbox])
    expect(existing.status === 1, "scaffold refuses an existing target")
    expect(existing.stderr.includes("already exists"), "the refusal says the target exists")

    // "plan" is the one reachable id whose derived role name ("plan reviewer") collapses onto a
    // base-roster name key (roleNameKey("Plan Reviewer")); it is refused BEFORE anything is written,
    // with the roster's own sentence, and it leaves nothing behind at the target.
    /** The one reachable id whose derived role name collides with a base-roster name key. */
    const collidingId = "plan"
    /** The refused collision run; it must leave nothing behind at the target. */
    const collision = runChild(["scaffold", collidingId, "--dir", sandbox])
    expect(collision.status === 1, `scaffold refuses the base-roster role collision for id "plan" (got ${collision.status})`)
    expect(collision.stderr.includes("would declare a role name the base roster already owns"), "the refusal is a CONTRACT refusal, not a CLI-defect message")
    expect(collision.stdout.includes("is already taken by the base roster"), "the refusal quotes the roster's own collision sentence")
    expect(collision.stderr.includes("nothing was written"), "the refusal states that nothing was written")
    expect(!existsSync(join(sandbox, collidingId)), "a refused scaffold leaves nothing at the target")
    expect(!readdirSync(sandbox).some((entry: string) => entry.startsWith(".mpd-ext-scaffold")), "a refused scaffold leaves no staging container behind")

    // 5. a deliberately broken extension: every defect is reported, exit is 1.
    /** A deliberately broken extension: every defect must be reported and the exit must be 1. */
    const broken = join(sandbox, "broken-ext")
    mkdirSync(broken, { recursive: true })
    writeFileSync(
      join(broken, MANIFEST_FILE),
      JSON.stringify({
        apiVersion: 1,
        id: "broken-ext",
        typoKey: true,
        contributes: {
          skills: [{ root: "../outside" }],
          mcp: [{ serverName: "not a name!", transport: "stdio", command: "node", surprise: 1 }],
          roles: [{ name: "Missing persona", persona: "personas/absent.md" }],
        },
      }),
    )
    /** The validate run over the broken extension: exit 1, one line per defect. */
    const brokenRun = runChild(["validate", broken])
    expect(brokenRun.status === 1, `validate exits 1 on a broken extension (got ${brokenRun.status})`)
    for (const needle of ["typoKey", "serverName", "contributes.skills[0].root", "escapes are rejected", "surprise", "persona file does not exist"]) {
      expect(brokenRun.stdout.includes(needle), `the broken run reports "${needle}"`)
    }

    // 6. the negative control on a COPY of the template: per-item errors, exit 1.
    /** A copy of the template whose manifest and frontmatter are broken: the negative control. */
    const brokenCopy = join(sandbox, "broken-copy")
    cpSync(scaffolded, brokenCopy, { recursive: true })
    writeFileSync(
      join(brokenCopy, MANIFEST_FILE),
      JSON.stringify({
        apiVersion: 1,
        id: "broken-copy",
        typoKey: true,
        contributes: {
          skills: [{ root: "skills" }],
          mcp: [{ serverName: "not a name!", transport: "stdio", command: "node", surprise: 1 }],
          roles: [{ name: "Missing persona", persona: "personas/absent.md" }],
        },
      }),
    )
    writeFileSync(join(brokenCopy, "skills", "demo-ext-skill", "SKILL.md"), "this file lost its YAML frontmatter\n")
    /** The negative control's validate run: exit 1 with the defects it was given. */
    const brokenCopyRun = runChild(["validate", brokenCopy])
    expect(brokenCopyRun.status === 1, `validate exits 1 on a deliberately broken copy of the template (got ${brokenCopyRun.status})`)
    for (const needle of ["typoKey", "surprise", "serverName", "persona file does not exist", "frontmatter"]) {
      expect(brokenCopyRun.stdout.includes(needle), `the broken copy reports "${needle}"`)
    }

    // 7. the shipped example validates.
    /** The shipped example, validated straight from the repository tree. */
    const example = runChild(["validate", join(repoRoot, "extensions", "mpd-ext-example")])
    expect(example.status === 0, `validate accepts extensions/mpd-ext-example (got ${example.status}): ${example.stderr.trim()}`)

    // 8. list never throws and sees the bundle plane.
    /** The discovery listing: it must never throw and must see the bundle plane. */
    const listed = runChild(["list"])
    expect(listed.status === 0, `list exits 0 (got ${listed.status})`)
    expect(listed.stdout.includes("bundle plane"), "list names the bundle plane")
    expect(listed.stdout.includes("mpd-ext-example"), "list sees the shipped example")

    // 9. usage guard.
    /** The bare invocation: it must print usage or fail, never stay silent. */
    const usage = runChild([])
    expect(usage.stdout.includes("usage") || usage.status !== 0, "no command prints usage or fails")

    if (process.exitCode !== 1) line(`[mpd-ext] --self-test passed (${checks} checks) [validator: ${validator.mode}]`)
  } finally {
    rmSync(sandbox, { recursive: true, force: true })
  }
}

/** The help text every unknown invocation prints; the same wording the header of this file documents. */
const USAGE = `usage: bun scripts/mpd-ext.ts <command>

  validate <dir|mpd-ext.json> [--plane project|user|bundle]
  scaffold <name> [--dir <path>] [--with-mcp]
  list
  --self-test
  --validator

Runs from a checkout (bun: the TypeScript validator sources) and from a packed
artifact (the packer-generated packages/mpd-ext-plugin/dist/validator.js, which
also works under plain node). --validator prints which one this run loaded.`

/** The CLI entry point: dispatch one command, or print usage and fail on an unknown one. */
async function main(): Promise<void> {
  /** The command-line arguments after the script path. */
  const argv = process.argv.slice(2)
  /** The requested command. */
  const command = argv[0]
  /** Read `--<name>`'s value: the next argument, or `undefined` when the flag is absent or last. */
  const flag = (name: string): string | undefined => {
    /** Position of the flag in the argument list, or -1. */
    const index = argv.indexOf(name)
    return index === -1 ? undefined : argv[index + 1]
  }
  if (command === "--self-test") return selfTest()
  if (command === "--validator") {
    line(`[mpd-ext] validator: ${validator.mode}`)
    /** The paths the loaded validator came from: the compiled entry, or every source target. */
    const target = validator.mode === "compiled" ? [COMPILED_VALIDATOR] : Object.values(SOURCE_VALIDATOR)
    for (const rel of target) line(`  ${resolve(repoRoot, rel.replace(/^\.\.\//, ""))}`)
    if (validator.mode === "compiled") for (const attempt of validator.attempts) line(`  (source path unavailable: ${attempt.target}: ${attempt.error})`)
    return
  }
  if (command === "validate") {
    /** `--plane` as typed, before the membership test decides whether it is a plane at all. */
    const requestedPlane = flag("--plane")
    // The membership test is the runtime check the original ran; `includes` cannot narrow a string to the
    // plane union, so the value that test just approved is carried in one assertion (and free text, being
    // absent from PLANES, still falls to "user" — the runtime behaviour is unchanged).
    const candidate = requestedPlane as MpdExtensionPlane
    /** The plane to validate against: a requested plane, else the documented "user" default. */
    const plane: MpdExtensionPlane = PLANES.includes(candidate) ? candidate : "user"
    return runValidate(argv[1], plane)
  }
  if (command === "scaffold") {
    return runScaffold(argv[1], { dir: flag("--dir"), withMcp: argv.includes("--with-mcp") })
  }
  if (command === "list") return runList()
  line(USAGE)
  if (command !== undefined && command !== "help" && command !== "--help") process.exitCode = 2
}

await main()
