// ============================================================================
// mpd LSP overlay — drift-guard anchor: mpd-lsp-overlay-v1
// ============================================================================
// Patched copy of upstream lsp-core src/lsp/language-mappings.ts. This file REPLACES
// the upstream file during the offline build (scripts/build-mcp.ts applies it
// over the freshly-copied lsp-core source), so it must stay a superset of the
// upstream baseline: keep every upstream export and entry intact. If the upstream
// file drifts (new export shape), the build fails loudly via the baselineExport
// check in build-mcp.ts — re-sync this overlay from the upstream file.

/** LSP SymbolKind numbers to the names a tool result prints, so a kind never surfaces as a bare number. */
export const SYMBOL_KIND_MAP: Record<number, string> = {
	1: "File",
	2: "Module",
	3: "Namespace",
	4: "Package",
	5: "Class",
	6: "Method",
	7: "Property",
	8: "Field",
	9: "Constructor",
	10: "Enum",
	11: "Interface",
	12: "Function",
	13: "Variable",
	14: "Constant",
	15: "String",
	16: "Number",
	17: "Boolean",
	18: "Array",
	19: "Object",
	20: "Key",
	21: "Null",
	22: "EnumMember",
	23: "Struct",
	24: "Event",
	25: "Operator",
	26: "TypeParameter",
};

/** LSP DiagnosticSeverity numbers to the severity labels the diagnostics report uses. */
export const SEVERITY_MAP: Record<number, string> = {
	1: "error",
	2: "warning",
	3: "information",
	4: "hint",
};

/** File extension to the LSP language id a server is asked to open the document as. */
export const EXT_TO_LANG: Record<string, string> = {
	".abap": "abap",
	".bat": "bat",
	".bib": "bibtex",
	".bibtex": "bibtex",
	".clj": "clojure",
	".cljs": "clojure",
	".cljc": "clojure",
	".edn": "clojure",
	".coffee": "coffeescript",
	".c": "c",
	".cpp": "cpp",
	".cxx": "cpp",
	".cc": "cpp",
	".c++": "cpp",
	".cs": "csharp",
	".css": "css",
	".d": "d",
	".pas": "pascal",
	".pascal": "pascal",
	".diff": "diff",
	".patch": "diff",
	".dart": "dart",
	".dockerfile": "dockerfile",
	".ex": "elixir",
	".exs": "elixir",
	".erl": "erlang",
	".hrl": "erlang",
	".fs": "fsharp",
	".fsi": "fsharp",
	".fsx": "fsharp",
	".fsscript": "fsharp",
	".gitcommit": "git-commit",
	".gitrebase": "git-rebase",
	".go": "go",
	".groovy": "groovy",
	".gleam": "gleam",
	".hbs": "handlebars",
	".handlebars": "handlebars",
	".hs": "haskell",
	".html": "html",
	".htm": "html",
	".ini": "ini",
	".java": "java",
	".jl": "julia",
	".js": "javascript",
	".jsx": "javascriptreact",
	".json": "json",
	".jsonc": "jsonc",
	".tex": "latex",
	".latex": "latex",
	".less": "less",
	".lua": "lua",
	".makefile": "makefile",
	makefile: "makefile",
	".md": "markdown",
	".markdown": "markdown",
	".m": "objective-c",
	".mm": "objective-cpp",
	".pl": "perl",
	".pm": "perl",
	".pm6": "perl6",
	".php": "php",
	".ps1": "powershell",
	".psm1": "powershell",
	".pug": "jade",
	".jade": "jade",
	".py": "python",
	".pyi": "python",
	".r": "r",
	".cshtml": "razor",
	".razor": "razor",
	".rb": "ruby",
	".rake": "ruby",
	".gemspec": "ruby",
	".ru": "ruby",
	".erb": "erb",
	".html.erb": "erb",
	".js.erb": "erb",
	".css.erb": "erb",
	".json.erb": "erb",
	".rs": "rust",
	".scss": "scss",
	".sass": "sass",
	".scala": "scala",
	".shader": "shaderlab",
	".sh": "shellscript",
	".bash": "shellscript",
	".zsh": "shellscript",
	".ksh": "shellscript",
	".sql": "sql",
	".svelte": "svelte",
	".swift": "swift",
	".ts": "typescript",
	".tsx": "typescriptreact",
	".mts": "typescript",
	".cts": "typescript",
	".mtsx": "typescriptreact",
	".ctsx": "typescriptreact",
	".xml": "xml",
	".xsl": "xsl",
	".yaml": "yaml",
	".yml": "yaml",
	".mjs": "javascript",
	".cjs": "javascript",
	".vue": "vue",
	".zig": "zig",
	".zon": "zig",
	".astro": "astro",
	".ml": "ocaml",
	".mli": "ocaml",
	".tf": "terraform",
	".tfvars": "terraform-vars",
	".hcl": "hcl",
	".nix": "nix",
	".typ": "typst",
	".typc": "typst",
	".ets": "typescript",
	".lhs": "haskell",
	".kt": "kotlin",
	".kts": "kotlin",
	".prisma": "prisma",
	".h": "c",
	".hpp": "cpp",
	".hh": "cpp",
	".hxx": "cpp",
	".h++": "cpp",
	".objc": "objective-c",
	".objcpp": "objective-cpp",
	".fish": "fish",
	".graphql": "graphql",
	".gql": "graphql",
};

/**
 * The language id to open a file as, resolved from its extension.
 *
 * @param ext - the file extension including its leading dot (for example `.ts`).
 * @returns the mapped language id, or `plaintext` when the extension is unknown.
 */
export function getLanguageId(ext: string): string {
	return EXT_TO_LANG[ext] ?? "plaintext";
}
