// Docs lane (team task t7 / contract lane t5) — the MEASUREMENT the docs transcribe.
//
// Everything the docs state numerically is derived here, from the two authorities the contract
// §5/§6 name: the registry (packages/mpd-agent-teams-plugin/lib/mpd-deltas.js, generated by
// `--write-registry`) and the live `//#region mpd-delta …` markers in the adopted tree.
// Run from the repo root: node evidence/agent-teams/adapter-wiring/docs/measure-counts.mjs
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { MPD_DELTAS } from "../../../../packages/mpd-agent-teams-plugin/lib/mpd-deltas.ts"

const ROOT = process.cwd()
const PLUGIN = "packages/mpd-agent-teams-plugin"
const BRIDGED = ["index.js", "capabilities.js", "harness-compat.js", "members.js", "command.js", "tools.js"]
const BRIDGE = "mpd-adapter-ctx.js"

const moment = new Date().toISOString()
console.log(`read at (UTC): ${moment}`)

// ── 1. the registry pair (the sentence R5 protects) ──────────────────────────────────────────
const files = new Set(MPD_DELTAS.map((delta) => delta.file))
console.log(`MPD_DELTAS.length = ${MPD_DELTAS.length}`)
console.log(`distinct registry files = ${files.size}`)
console.log(`registry keys of entry 0 = ${Object.keys(MPD_DELTAS[0]).join(",")}`)
console.log(`entries carrying a "create" key = ${MPD_DELTAS.filter((delta) => "create" in delta).length}`)

// ── 2. the live markers (nesting-aware pairing, the gate's own shape) ────────────────────────
const BEGIN = /^\s*\/\/#region\s+(mpd-delta\s+\S+)/
const END = /^\s*\/\/#endregion\b/
function markersOf(rel) {
    const ids = []
    const stack = []
    for (const line of readFileSync(join(ROOT, rel), "utf8").split("\n")) {
        const begin = BEGIN.exec(line)
        if (begin !== null) {
            stack.push(begin[1])
            ids.push(begin[1])
            continue
        }
        if (END.test(line)) stack.pop()
    }
    return { ids, unclosed: stack.length }
}
let bridgedMarkers = 0
const bridgedIds = new Set()
for (const name of BRIDGED) {
    const { ids, unclosed } = markersOf(`${PLUGIN}/lib/${name}`)
    bridgedMarkers += ids.length
    for (const id of ids) bridgedIds.add(id)
    console.log(`  ${name}: ${ids.length} marker(s), unclosed=${unclosed}`)
}
const bridge = markersOf(`${PLUGIN}/lib/${BRIDGE}`)
console.log(`six bridged files: ${bridgedMarkers} markers / ${bridgedIds.size} distinct ids`)
console.log(`${BRIDGE}: ${bridge.ids.length} marker(s) [${bridge.ids.join(", ")}]`)
console.log(`including the bridge module: ${bridgedMarkers + bridge.ids.length} markers / ${new Set([...bridgedIds, ...bridge.ids]).size} distinct ids`)

// ── 2b. the ADAPTER-* markers specifically (the set the docs' bridge section names) ───────────
let adapterMarkers = 0
const adapterIds = new Set()
let crossFileDuplicate = 0
for (const name of [...BRIDGED, BRIDGE]) {
    const ids = markersOf(`${PLUGIN}/lib/${name}`).ids
        .map((id) => id.replace(/^mpd-delta\s+/, ""))
        .filter((id) => id.startsWith("adapter-"))
    adapterMarkers += ids.length
    for (const id of ids) {
        if ([...BRIDGED, BRIDGE].filter((other) => markersOf(`${PLUGIN}/lib/${other}`).ids.some((raw) => raw.replace(/^mpd-delta\s+/, "") === id)).length > 1) crossFileDuplicate += 1
        adapterIds.add(id)
    }
    console.log(`  ${name}: ${ids.length} adapter-* marker(s)`)
}
const sixOnly = [...BRIDGED].flatMap((name) => markersOf(`${PLUGIN}/lib/${name}`).ids
    .map((id) => id.replace(/^mpd-delta\s+/, ""))
    .filter((id) => id.startsWith("adapter-")))
console.log(`six bridged files: ${sixOnly.length} adapter-* markers / ${new Set(sixOnly).size} distinct ids`)
console.log(`including the bridge module: ${adapterMarkers} adapter-* markers / ${adapterIds.size} distinct ids (cross-file repeats: ${crossFileDuplicate})`)

// ── 3. the six files' adapter-* region ids, in registry order (the docs list them) ────────────
for (const name of [...BRIDGED, BRIDGE]) {
    const ids = MPD_DELTAS.filter((delta) => delta.file.endsWith(`/${name}`)).map((delta) => delta.id.replace(/^mpd-delta\s+/, ""))
    console.log(`${name}: ${ids.length} registered region(s) — ${ids.join(", ")}`)
}

// ── 4. the fourteen adapter methods + their capability flags (AC1's surface) ─────────────────
const src = readFileSync(join(ROOT, "packages/mpd-dsh-adapter-plugin/src/index.ts"), "utf8")
const METHODS = ["registerHostTool", "subagentRuntime", "subagentProvider", "subagentProviders",
    "startContinuableAgent", "interruptAgent", "llmListModels", "llmResolveCallConfig",
    "registerPromptSection", "agentScope", "startAgentTurn", "cancelAgentTurn",
    "steerAgentTurn", "injectAgentMessage"]
for (const method of METHODS) {
    const declared = src.includes(`${method}(`)
    const implemented = new RegExp(`^\\s{4,}${method}\\(`, "m").test(src)
    console.log(`  method ${method}: declared=${declared} implemented=${implemented}`)
}
const FLAGS = ["toolsRegisterHost", "subagents", "subagentsProvider", "subagentsContinuable",
    "subagentsInterrupt", "llmListModels", "llmResolveCallConfig", "systemPromptSection",
    "agentScope", "agentTurnStart", "agentTurnCancel", "agentTurnSteer", "agentTurnInject"]
for (const flag of FLAGS) console.log(`  flag ${flag}: ${new RegExp(`^\\s+${flag}: boolean`, "m").test(src)}`)

// ── 5. the members.js residual's counted lines (the closure claim must name it) ─────────────
const members = readFileSync(join(PLUGIN, "lib/members.ts"), "utf8")
const residualLines = []
for (const line of members.split("\n")) {
    if (/\bchildCtx\b/.test(line) && line.trim() !== "" && !line.trim().startsWith("*") && !line.trim().startsWith("//")) {
        residualLines.push(line.trim())
    }
}
console.log(`members.js childCtx residual lines = ${residualLines.length}`)
for (const line of residualLines) console.log(`  ${line}`)
