#!/usr/bin/env node
// mount-lazy-live.mjs — t40's mounted-boot proof that T-50's lazy adapter resolution is LIVE.
//
// WHAT THIS PROVES (and what it does NOT):
//   A) STANDARD composition: the rebuilt dists mount in a real dsh boot (isolated DSH_HOME +
//      sandboxed HOME + sandboxed workspace), the rows report `adapterIdentity=mounted:mpdDsh`,
//      and there is NO fallback / not-yet-active line and NO apply-crash signature. The healthy
//      path is unchanged.
//   B/C) DISCRIMINATING composition: a deliberately SLOW provider row (it provides `mpdDsh` and
//      keeps its own fiber non-ACTIVE for SLOW_MS) puts the consumer rows inside the exact
//      transient window T-50 describes — the same window six clean boots never opened. Same
//      composition, same rows, only the DIST BYTES differ:
//        B (RED)  = the pre-t12 dists (git HEAD): `adapterIdentity=fallback:createDshAdapter`
//                   and the wrong diagnosis "fix the ROW ORDER";
//        C (GREEN)= the rebuilt dists: `adapterIdentity=pending:provider-not-active` and the
//                   honest line "ADAPTER NOT YET ACTIVE … transient miss needs NO row-order change".
//      This is a CONSTRUCTED window, not an observed production defect: the register's bound
//      (6/6 clean boots never opened it) stands, and this driver claims nothing more than that the
//      new code path is live, that the warning separates the two miss modes, and that the runtime
//      no longer pins a private adapter for a provider that is merely still starting.
//
// `dsh --dump-config` is NOT used anywhere: every assertion is read off a real boot log.
import { execFileSync, spawn } from "node:child_process"
import { cpSync, existsSync, mkdirSync, openSync, readFileSync, rmSync, symlinkSync, writeFileSync, mkdtempSync } from "node:fs"
import { homedir, tmpdir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = dirname(dirname(dirname(dirname(HERE))))
const RAW = join(HERE, "raw")
const SLOW_MS = 6000

const { sandboxWorkspace } = await import(pathToFileURL(join(REPO, "skills/dsh-qa/scripts/lib/workspace-isolation.mjs")).href)

const ADAPTER_DIST = join(REPO, "packages/mpd-dsh-adapter-plugin/dist/index.js")
const EXT_DIST = join(REPO, "packages/mpd-ext-plugin/dist/index.js")
const ROLES_DIST = join(REPO, "packages/mpd-roles-plugin/dist/index.js")

const CRASH_SIGNATURES = ["unsupported JSON schema", "JsonSchemaError", "plugin tree failed to load", "failed to apply loader entry"]
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

function extractOldDist() {
  const dir = join(RAW, "old-dist")
  mkdirSync(dir, { recursive: true })
  const files = {
    ext: [join(dir, "ext-index.js"), "packages/mpd-ext-plugin/dist/index.js"],
    roles: [join(dir, "roles-index.js"), "packages/mpd-roles-plugin/dist/index.js"],
  }
  for (const [key, [out, repoPath]] of Object.entries(files)) {
    const bytes = execFileSync("git", ["show", "HEAD:" + repoPath], { cwd: REPO, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 })
    writeFileSync(out, bytes)
    files[key] = [out, repoPath]
  }
  return { ext: files.ext[0], roles: files.roles[0] }
}

function writeSlowProvider() {
  const file = join(RAW, "slow-adapter-row.mjs")
  writeFileSync(file, [
    "// Generated by mount-lazy-live.mjs: a provider row that provides `mpdDsh` and then keeps its",
    "// own fiber non-ACTIVE for SLOW_MS, so a SIBLING consumer row's first use lands inside the",
    "// transient window (registered-but-not-ACTIVE) that T-50 is about.",
    "import { createDshAdapter, SERVICE_NAME } from " + JSON.stringify(ADAPTER_DIST),
    "export const name = 't40-slow-adapter-probe'",
    "export async function apply(ctx) {",
    "  const adapter = createDshAdapter(ctx)",
    "  ctx.provide(SERVICE_NAME, adapter)",
    "  console.log('[t40-slow-adapter] mpdDsh provided; fiber stays non-ACTIVE for " + SLOW_MS + " ms')",
    "  await new Promise((resolve) => setTimeout(resolve, " + SLOW_MS + "))",
    "  console.log('[t40-slow-adapter] apply returning — provider fiber becomes ACTIVE')",
    "}",
    "",
  ].join("\n"))
  return file
}

function writePatch(name, rows) {
  const file = join(RAW, name)
  // Patch grammar (AGENTS.md §8): an id that ALREADY exists is a top-level override, a NEW id must
  // be emitted under `- insert:` with the row indented by two spaces. These probes are new ids.
  const body = rows.map((row) => {
    const lines = ["  - id: " + row.id, "    name: " + JSON.stringify(row.name)]
    if (row.config !== undefined) lines.push("    config: " + JSON.stringify(row.config))
    return lines.join("\n")
  }).join("\n")
  writeFileSync(file, "- insert:\n" + body + "\n")
  return file
}

function makeSandbox(tag, bundles) {
  const sandbox = mkdtempSync(join(tmpdir(), "mpd-t40-" + tag + "-"))
  const home = join(sandbox, "home")
  const userHome = join(sandbox, "userhome")
  const profile = join(home, "profiles", "w")
  mkdirSync(join(profile, "node_modules", "@mpd-dsh"), { recursive: true })
  mkdirSync(userHome, { recursive: true })
  const creds = join(homedir(), ".dsh", ".credentials.yaml")
  if (existsSync(creds)) cpSync(creds, join(home, ".credentials.yaml"))
  const settings = join(homedir(), ".dsh", "settings.yaml")
  if (existsSync(settings)) cpSync(settings, join(home, "settings.yaml"))
  // A checkout install IS a link: node_modules/@mpd-dsh/mpd -> the repo (the same shape
  // `dsh plugin add <repo>` writes), so the bundle patch's rows resolve through the exports map.
  symlinkSync(REPO, join(profile, "node_modules", "@mpd-dsh", "mpd"), "dir")
  writeFileSync(join(profile, "package.json"), JSON.stringify({
    name: "dsh-profile-w", private: true, dependencies: {}, dsh: { profile: { bundles } },
  }, null, 2))
  if (join(home).startsWith(join(homedir(), ".dsh"))) throw new Error("isolation assertion failed: DSH_HOME points at the real home")
  return { sandbox, home, userHome, profile, ws: sandboxWorkspace(sandbox) }
}

/** Boot one sandbox, wait for the interesting lines (or the deadline), kill, return the log. */
async function boot({ tag, bundles, patchFiles, port, waitFor, deadlineMs = 120000 }) {
  const sb = makeSandbox(tag, bundles)
  const logPath = join(RAW, tag + ".boot.log")
  const fd = openSync(logPath, "w")
  const args = ["--profile", "w", ...patchFiles.flatMap((p) => ["--patch", p]), "--port", String(port), "--no-open"]
  const child = spawn("dsh", args, { env: { ...process.env, DSH_HOME: sb.home, HOME: sb.userHome }, cwd: sb.ws, stdio: ["ignore", fd, fd] })
  const readLog = () => { try { return readFileSync(logPath, "utf8") } catch { return "" } }
  const deadline = Date.now() + deadlineMs
  let seen = false
  while (Date.now() < deadline) {
    await sleep(1000)
    const log = readLog()
    if (waitFor.every((needle) => log.includes(needle))) { seen = true; break }
  }
  child.kill("SIGTERM")
  await sleep(500)
  const log = readLog()
  return { tag, sandbox: sb.sandbox, logPath, args, seen, log }
}

function j(result, pattern) {
  const m = pattern.exec(result.log)
  return m === null ? null : m[1]
}

const verdicts = []
const run = async () => {
  mkdirSync(RAW, { recursive: true })
  const oldDist = extractOldDist()
  const slowRow = writeSlowProvider()

  // ── A) STANDARD composition: the real bundle, rebuilt dists, nothing slowed down.
  const a = await boot({
    tag: "A-standard",
    bundles: ["@deepseek-ai/dsh-base", "@deepseek-ai/dsh-web-app", "@mpd-dsh/mpd"],
    patchFiles: [],
    port: 3221,
    waitFor: ["[mpd-ext] mpdExtensions provided", "[mpd-roles] mpdRoles provided"],
  })
  verdicts.push({
    id: "A-standard-composition",
    expectation: "both rows mount, report mounted:mpdDsh, zero warnings, zero crash signatures",
    extIdentity: j(a, /\[mpd-ext\][^\n]*adapterIdentity=([A-Za-z0-9:_.-]+)/),
    rolesIdentity: j(a, /\[mpd-roles\][^\n]*adapterIdentity=([A-Za-z0-9:_.-]+)/),
    adapterLine: /\[mpd-dsh-adapter\] mpdDsh provided/.test(a.log),
    fallbackLines: (a.log.match(/ADAPTER FALLBACK/g) ?? []).length,
    notYetActiveLines: (a.log.match(/ADAPTER NOT YET ACTIVE/g) ?? []).length,
    crashSignatures: CRASH_SIGNATURES.filter((s) => a.log.includes(s)),
    rawLog: a.logPath,
  })

  // ── B) RED: same slow-provider composition, PRE-t12 dist bytes (git HEAD).
  const patchRed = writePatch("slow-provider-red.yml", [
    { id: "mpd-ext-red", name: oldDist.ext, config: { quiet: false } },
    { id: "mpd-roles-red", name: oldDist.roles, config: {} },
    { id: "t40-slow-adapter-red", name: slowRow, config: {} },
  ])
  const b = await boot({
    tag: "B-red-old-dist",
    bundles: ["@deepseek-ai/dsh-base", "@deepseek-ai/dsh-web-app"],
    patchFiles: [patchRed],
    port: 3222,
    waitFor: ["[mpd-ext] mpdExtensions provided", "[mpd-roles] mpdRoles provided"],
  })
  verdicts.push({
    id: "B-red-pre-t12-dist",
    expectation: "the OLD dist pins the fallback and blames the ROW ORDER",
    extIdentity: j(b, /\[mpd-ext\][^\n]*adapterIdentity=([A-Za-z0-9:_.-]+)/),
    rolesIdentity: j(b, /\[mpd-roles\][^\n]*adapterIdentity=([A-Za-z0-9:_.-]+)/),
    fallbackLines: (b.log.match(/ADAPTER FALLBACK/g) ?? []).length,
    rowOrderHint: /fix the ROW ORDER/.test(b.log),
    notYetActiveLines: (b.log.match(/ADAPTER NOT YET ACTIVE/g) ?? []).length,
    slowProviderWindow: /t40-slow-adapter\] mpdDsh provided/.test(b.log),
    rawLog: b.logPath,
  })

  // ── C) GREEN: identical composition, REBUILT dist bytes.
  const patchGreen = writePatch("slow-provider-green.yml", [
    { id: "mpd-ext-green", name: EXT_DIST, config: { quiet: false } },
    { id: "mpd-roles-green", name: ROLES_DIST, config: {} },
    { id: "t40-slow-adapter-green", name: slowRow, config: {} },
  ])
  const c = await boot({
    tag: "C-green-new-dist",
    bundles: ["@deepseek-ai/dsh-base", "@deepseek-ai/dsh-web-app"],
    patchFiles: [patchGreen],
    port: 3223,
    waitFor: ["[mpd-ext] mpdExtensions provided", "[mpd-roles] mpdRoles provided"],
  })
  verdicts.push({
    id: "C-green-rebuilt-dist",
    expectation: "the NEW dist names the not-yet-ACTIVE provider and never claims a row-order fix",
    extIdentity: j(c, /\[mpd-ext\][^\n]*adapterIdentity=([A-Za-z0-9:_.-]+)/),
    rolesIdentity: j(c, /\[mpd-roles\][^\n]*adapterIdentity=([A-Za-z0-9:_.-]+)/),
    notYetActiveLines: (c.log.match(/ADAPTER NOT YET ACTIVE/g) ?? []).length,
    rowOrderHint: /fix the ROW ORDER/.test(c.log),
    fallbackLines: (c.log.match(/ADAPTER FALLBACK/g) ?? []).length,
    slowProviderWindow: /t40-slow-adapter\] mpdDsh provided/.test(c.log),
    rawLog: c.logPath,
  })

  const pass = {
    A: verdicts[0].extIdentity === "mounted:mpdDsh" && verdicts[0].rolesIdentity === "mounted:mpdDsh"
      && verdicts[0].fallbackLines === 0 && verdicts[0].notYetActiveLines === 0 && verdicts[0].crashSignatures.length === 0,
    B: verdicts[1].extIdentity === "fallback:createDshAdapter" && verdicts[1].rowOrderHint === true,
    C: verdicts[2].extIdentity === "pending:provider-not-active" && verdicts[2].notYetActiveLines > 0 && verdicts[2].rowOrderHint === false,
  }
  const ok = pass.A && pass.B && pass.C
  writeFileSync(join(HERE, "mount-result.json"), JSON.stringify({
    ok,
    generatedAt: new Date().toISOString(),
    slowProviderWindowMs: SLOW_MS,
    claims: {
      proves: [
        "the rebuilt dists mount in a real dsh boot (isolated DSH_HOME + sandboxed HOME + sandboxed workspace) with no apply-crash signature",
        "in the standard composition the healthy path is unchanged: mounted:mpdDsh on both rows, zero fallback/not-yet-active lines",
        "under a CONSTRUCTED transient window the rebuilt dists diagnose 'provider not yet ACTIVE' and never claim a row-order fix, while the pre-t12 dists pin fallback:createDshAdapter and blame the ROW ORDER",
      ],
      does_not_prove: [
        "that the window ever opens in a production boot (the register's bound stands: six clean boots never opened it; the window here is forced by a deliberately slow provider row)",
        "the post-activation recovery of the same facade in a live boot — the service fields are captured when the service object is built, so recovery is proven on the shipped bytes by the dist-level cordis probe and by packages/mpd-dsh-adapter-plugin/test/adapter.test.ts",
      ],
    },
    pass,
    verdicts,
  }, null, 2) + "\n")
  for (const v of verdicts) console.log("[" + v.id + "] " + (v.rawLog === undefined ? "" : JSON.stringify({ ext: v.extIdentity, roles: v.rolesIdentity, fallback: v.fallbackLines, notYetActive: v.notYetActiveLines, rowOrder: v.rowOrderHint })))
  console.log("[mount-lazy-live] ok=" + ok + " pass=" + JSON.stringify(pass))
  if (!ok) process.exit(1)
}

await run()
